### ISSUE TITLE
I can't build successfully, why? I use jdk 8

### ISSUE THREAD

**Issue by RebeWu** [jknack/handlebars.java#1089]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 s - in com.github.jknack.handlebars.i229.Issue229
[INFO] Running com.github.jknack.handlebars.i289.Issue289
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.452 s - in com.github.jknack.handlebars.i289.Issue289
[INFO] Running com.github.jknack.handlebars.ToStringTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in com.github.jknack.handlebars.ToStringTest
[INFO] Running com.github.jknack.handlebars.HandlebarsExceptionTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in com.github.jknack.handlebars.HandlebarsExceptionTest
[INFO] Running com.github.jknack.handlebars.FalsyValueTest
[INFO] Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 s - in com.github.jknack.handlebars.FalsyValueTest
[INFO] Running com.github.jknack.handlebars.JavaVersionTest
[WARNING] Tests run: 10, Failures: 0, Errors: 0, Skipped: 9, Time elapsed: 0.002 s - in com.github.jknack.handlebars.JavaVersionTest
[INFO] Running com.github.jknack.handlebars.i270.Issue270
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in com.github.jknack.handlebars.i270.Issue270
[INFO] Running com.github.jknack.handlebars.i367.Issue367
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in com.github.jknack.handlebars.i367.Issue367
[INFO] Running com.github.jknack.handlebars.CollectionsLengthTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in com.github.jknack.handlebars.CollectionsLengthTest
[INFO] Running com.github.jknack.handlebars.ContextTest
[INFO] Tests run: 16, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in com.github.jknack.handlebars.ContextTest
[INFO] Running com.github.jknack.handlebars.IfBlockTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in com.github.jknack.handlebars.IfBlockTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   ClassPathTemplateLoaderTest.setBasePath:71 » FileNotFound /mustache/specs/comm...
[ERROR]   ClassPathTemplateLoaderTest.setBasePathWithDashDash:78 » FileNotFound /mustach...
[ERROR]   ClassPathTemplateLoaderTest.subFolder:50 » FileNotFound /mustache/specs/commen...
[ERROR]   ClassPathTemplateLoaderTest.subFolderwithDashAtBeginning:58 » FileNotFound /mu...
[ERROR]   FileTemplateLoaderTest.setBasePath:72 » IllegalArgument File not found: src/te...
[ERROR]   FileTemplateLoaderTest.setBasePathWithDash:80 » IllegalArgument File not found...
[ERROR]   FileTemplateLoaderTest.subFolder:51 » FileNotFound src/test/resources/mustache...
[ERROR]   FileTemplateLoaderTest.subFolderwithDashAtBeginning:59 » FileNotFound src/test...
[ERROR]   ServletContextTemplateLoaderTest.setBasePath:70 » FileNotFound /comments.yml
[ERROR]   ServletContextTemplateLoaderTest.setBasePathWithDash:82 » FileNotFound /commen...
[ERROR]   ServletContextTemplateLoaderTest.subFolder:35 » FileNotFound /mustache/specs/c...
[ERROR]   ServletContextTemplateLoaderTest.subFolderwithDashAtBeginning:47 » FileNotFound
[ERROR]   CommentsTest.data:33->SpecTest.data:106->SpecTest.data:126 » FileNotFound src/...
[ERROR]   DelimitersTest.data:33->SpecTest.data:106->SpecTest.data:126 » FileNotFound sr...
[ERROR]   InterpolationTest.data:33->SpecTest.data:106->SpecTest.data:126 » FileNotFound
[ERROR]   InvertedTest.data:33->SpecTest.data:106->SpecTest.data:126 » FileNotFound src/...
[ERROR]   LambdasTest.data:148->SpecTest.data:106->SpecTest.data:126 » FileNotFound src/...
[ERROR]   PartialsTest.data:67->SpecTest.data:106->SpecTest.data:126 » FileNotFound src/...
[ERROR]   SectionsTest.data:33->SpecTest.data:106->SpecTest.data:126 » FileNotFound src/...
[INFO]
[ERROR] Tests run: 879, Failures: 0, Errors: 19, Skipped: 15
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Handlebars.java 4.3.1:
[INFO]
[INFO] Handlebars.java .................................... SUCCESS [  0.006 s]
[INFO] Handlebars ......................................... FAILURE [ 42.223 s]
[INFO] Handlebars Helpers ................................. SKIPPED
[INFO] Handlebars Spring MVC .............................. SKIPPED
[INFO] A Jackson 2.x helper ............................... SKIPPED
[INFO] Humanize helpers ................................... SKIPPED
[INFO] A standalone Handlebars Server ..................... SKIPPED
[INFO] Handlebars Guava Cache ............................. SKIPPED
[INFO] Handlebars Caffeine Cache .......................... SKIPPED
[INFO] Handlebars.js maven plugin ......................... SKIPPED
[INFO] Handlebars.js maven plugin tests ................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:32 min
[INFO] Finished at: 2023-12-31T02:51:14Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project handlebars: There are test failures.
[ERROR]
[ERROR] Please refer to /home/project/handlebars.java-4.3.1/handlebars/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

**Comment by jknack** [comment]
there is a git submodule that requires to be fetched. I changed the build process to fetch when missing
