### ISSUE TITLE
block helper must catch IOException

### ISSUE THREAD

**Issue by jknack** [jknack/handlebars.java#178]
If an `IOException` occurs in the block helper during the resolution of a partial, the default block body must be used.

**Comment by sbuettner** [comment]
I think this behavior is problematic. Block helpers should use another way to resolve partials that are defined in Layouts for template inheritance. The current behavior queries the template compiler and issues a ```TemplateLoader.sourceAt``` method call which then leads to an ```IOException```. This means that for a layout with 3 blocks the ```sourceAt``` method gets called three times which then could lead to 3 database calls when the templates stored inside of a db etc.

**Comment by jknack** [comment]
happy to hear an alternative solution!

but also, what you're describing is the way it works for "external partials". This isn't the case for "inline partials" (which is in my mind the majority of use cases)

**Comment by sbuettner** [comment]
Hi @jknack. First thank you for the great library.

Just curious, aren´t partials of type ```TagType.SECTION``` always external partials?

**Comment by jknack** [comment]
nope, tag types has nothing to do with partials :)

for example, default expression: ```{{ }}``` has a type of ```TagType.VAR```, while expressions like ```{{# }}``` has a ```TagType.SECTION```

external partials are those that need to be loaded from somewhere: fs, db, etc... and they have a form of ```{{> }}```

"inline partial" are those defined via ```block``` and ```partial``` helpers. These two helpers were created to provide "template inheritance" in handlebars.

base.html:
```
<header>
{{block "header"}}
</header>
```

home.html:
```
{{#partial "header"}}HomePage{{/partial}}
```

This is what I call the "normal" use case and here there is NO template lookup, bc partials are defined within the template

**Comment by sbuettner** [comment]
Ok, i think i narrowed my issue. Depending on the position of the partial inclusion i get different results. This is an example layout template:
```
Title: {{#block "title"}}The Title{{/block}}
Block: {{#block "body"}}The body{{/block}}
```

Now i can use the following template to get the correct behavior: 
```
{{#partial "title"}}My name is {{name}}{{/partial}}
{{#partial "body"}}My age is {{age}}{{/partial}}
{{> layout}}
```

If i change the position of the ```{{> layout}}``` tag like this: 
```
{{> layout}}
{{#partial "title"}}My name is {{name}}{{/partial}}
{{#partial "body"}}My age is {{age}}{{/partial}}
```
The template loader will now try to load the template and if it doesnt exist (IOException) the inline partial will be used.

This was my confusion because it depends on the position of the partial inclusion tag how the partials are resolved.

**Comment by jknack** [comment]
exactly!

inline partials must be declared BEFORE the base template.

glad you figure it out!

**Comment by sbuettner** [comment]
Ok, but if we can differentiate between inline and external partials we could lookup inline partials without catching the IOException or am iam wrong here?

**Comment by jknack** [comment]
block helper has 3 options to resolve a template

1. use an inline partial
2. if 1) fails, try to load a real partial (external) using the name of the inline partial
3. if 1) 2) fails it will use the default body as template

So, no . I don't think it is possible to catch for the IOException, bc it must render the default template.

**Comment by sbuettner** [comment]
Ok, let me try to rephrase it.

Why do we need to ask the ```TemplateLoader``` when we know, that it is an inline partial and that the content is defined inside the tag?

**Comment by jknack** [comment]
you're missing the 2) use case

p1.html:

```
partial 1
```

base.html
```
{{block "p1"}}
```

t1.html
```
{{> base}}
```

here it will fill block p1 with the content of p1.html.

This might look odd to you, but think there are a few use cases for this but also (most important) block/partial helpers work as in handlebars.js (but of course in js all the partial are inline, they don't have access to fs, db, etc..)

**Comment by sbuettner** [comment]
But wouldn't you use ```{{> p1}}``` inside *base.html* in this case?

**Comment by sbuettner** [comment]
Ok, so due to the responsibility of the block helper to do the same as the ```{{> ...}}```directive you have to do the lookup?

**Comment by jknack** [comment]
yea, yea and I got your point. As I said, I did this to allow handlebars.java works as handlebars.js, and after discussing the issue with you was probably a bad decision :). Sadly, I can't change it now.

so, go and override the block helper it is just a few lines of code and it will works as you expect

**Comment by sbuettner** [comment]
Ok, no problem. Thank you for the clarification and the great library.
