### ISSUE TITLE
Add "format" hash to "dateFormat" helper

### ISSUE THREAD

**Issue by rage-shadowman** [jknack/handlebars.java#241]
If the "dateFormat" helper is used without specifying the format as the first option, it should check the hash for a "format" entry and use that if it exists before defaulting to "medium".

Most of the javascript dateFormat helpers I am seeing in a google search make use of a "format" hash entry instead. It would be nice to support that as it makes the code a little more readable IMO.

...or maybe just an alternative "dateFormat" that expects the "format" entry in the hash rather than as the first option...

**Comment by pradeepgmishra** [comment]
I am getting following error when using dateFormat-

com.github.jknack.handlebars.HandlebarsException: inline@348cb2b:355:116: java.lang.IllegalArgumentException: found '2015-12-23T17:26:16.258-0500', expected 'date'

It is not able to recognise 2015-12-23T17:26:16.258-0500 as date, what can I do?

**Comment by jknack** [comment]
The `dateFormat` helper expects a `java.util.Date` seems your date is a `String`?

If so, then you need a custom helper that first parse the `String` date and then format the resulting `Date`
