### ISSUE TITLE
broken link on main page

### ISSUE THREAD

**Issue by uwemaurer** [jknack/handlebars.java#252]
this link is not working anymore:
http://thejohnfreeman.com/blog/2012/03/23/template-inheritance-for-handlebars.html

**Comment by karlhorky** [comment]
@thejohnfreeman [will upload it this weekend](https://github.com/jknack/handlebars.java/blob/gh-pages/reuse.html). 

Can we open this ticket again to fix the link here? https://github.com/jknack/handlebars.java/blob/gh-pages/reuse.html

**Comment by karlhorky** [comment]
In the meantime for anyone looking for this, I saved a version from the Internet Archive here: https://gist.github.com/karlhorky/e9f428b54648f62a9f4f
