### ISSUE TITLE
Joda DateTime Value resolver not kicking in

### ISSUE THREAD

**Issue by husayt** [jknack/handlebars.java#332]
i need to resolve Joda DateTime objects to long, so I have implemented the following `ValueResolver`. 
```java
public enum DateTimeResolver implements ValueResolver {
    INSTANCE;

    @Override
    public Object resolve(Object context, String name) {
        return UNRESOLVED;
    }

    @Override
    public Object resolve(Object context) {
        if (context instanceof ReadableInstant) {
            return ((ReadableInstant) context).getMillis();
        }
        return UNRESOLVED;
    }

    @Override
    public Set<Map.Entry<String, Object>> propertySet(Object context) {
        return Collections.emptySet();
    }
}
```

I register the following resolvers:
```java
ValueResolver[] valueResolvers = {DateTimeResolver.INSTANCE,  MapValueResolver.INSTANCE, JavaBeanValueResolver.INSTANCE,};
```

It works when I pass DateTime object as context.  So when I try to pass DateTime object as context 
```java
hbs.compileInline("time is {{now}}").apply(DateTime.now())
```
 it works. But when I pass DateTime as map value, i.e.

```java
hbs.compileInline("time is {{this.date}}").apply(ImmutableMap.of("date", DateTime.now()))
```
 it doesn't recognise that date value is DateTime and outputs is as String, when we expect it be long.

I will very appreciate for your assistance.
Thanks

**Comment by jknack** [comment]
I screw up the commit, but the fix is here: https://github.com/jknack/handlebars.java/commit/66206701521f694a2c7a751d98f1acd66b3bb768
