### ISSUE TITLE
Accessing Raw template text in HelperClasses

### ISSUE THREAD

**Issue by ahmadux** [jknack/handlebars.java#341]
I am still starting out so bear with me if my questions is too basic.

I wanted to know if it is possible to access the raw inner text between tags. <b>For Example:</b>
<pre>
{{#iterations}}&lt;div&gt;{{attribute1}{{attribute2}}&lt;/div&gt;{{/iterations}}
</pre>

Using <pre>options.fn()</pre> gives me 
<pre>
&lt;div&gt;&lt;/div&gt;
</pre>
I want 
<code>
&lt;div&gt;{{attribute1}{{attribute2}}&lt;/div&gt;
</code>

So, is there a way to access the raw data?

**Comment by jknack** [comment]
inside a helper you do: ```options.fn.text()``` :)

can you edit the subject to match the question?
tks

**Comment by ahmadux** [comment]
ty
