### ISSUE TITLE
Question: Modifying/keeping list of values outputted

### ISSUE THREAD

**Issue by joshq00** [jknack/handlebars.java#342]
I'm trying to build a small framework for dynamically creating prepared statements using handlebars.

I need to modify the written values for variables, but later be able to reference the (Object) value.

I'm hoping you have some insight of a way to access to these values after calling `template.apply(...)`

Here's an example of a template (the passed in context is the search-criteria)

**Context**
```json
{
   "limit": 50,
   "states": [ "GA", "FL", "AL", "LA" ]
}
```

**Template**
```handlebars
SELECT
...
WHERE
...
{{#if states}}
   AND EXISTS (
      SELECT 1
      FROM address a
      WHERE
         u.id = a.user_id AND (
            {{#states}}
               a.state = {{.}}
               {{#unless @last}}
                  OR
               {{/unless}}
            {{/states}}
         )
   )
{{/if}}
AND rownum < {{limit}}
```

**Output**
```sql
SELECT
...
WHERE
...
   AND EXISTS (
      SELECT 1
      FROM address a
      WHERE
         u.id = a.user_id AND (
               a.state = ? -- GA
                  OR
               a.state = ? -- FL
                  OR
               a.state = ? -- AL
                  OR
               a.state = ? -- LA
         )
   )
AND rownum < ?
```

or without any "states" criteria
```sql
SELECT
...
WHERE
...
AND rownum < ?
```
------

I can get the `?` working by simply using an `EscapingStrategy`, but I need access to the (original) values that they are substituting.

Having the `PreparedStatement`, I will need to pass in `[ "GA", "FL", "AL", "LA", 50 ]` -- keeping their original types.

Any ideas? I was looking at value resolver and providing a UUID in place of a value, but this will mess with \#if \#each etc, I need to ONLY substitute template outputs

Thanks in advance!

**Comment by jknack** [comment]
not sure I get it, but in my you have two phases

1. render the template with handlebars.
2. build the prepared statement. At this stage, why can't just access to your model and get the data you need?

**Comment by joshq00** [comment]
I can, but the point is making that automated - "Your template outputted ?'s in place of [Context.a, context.a, context.c, context.c[0], context.c[1], context.c[2]]" and getting those back.

To access the model/get the data I need, I'd need to manually make an array of "what variables were replaced" -- and might as well use a plain StringBuilder, strongly binding criteria to a template. If I want another query to use the same context, I'd have to implement (again) building the array/query.

Maybe a more descriptive example:
**Context**
```json
{
   "color": [ "black", "silver" ],
   "description": null,
   "manufacturer": [ "Samsung" ],
}
```
**Template**
```handlebars
select ... from ...
where 1=1
{{!-- looking for certain colors --}}
{{#if color}}
   AND color in ( {{#colors}}{{.}}{{/color}} )
{{/if}}
{{!-- looking for products matching a specific description --}}
{{#if description}}
   AND description like {{description}}
{{/if}}
{{!-- looking for certain manufacturers --}}
{{#if manufacturer}}
   AND manufacturer in ( {{#manufacturer}}{{.}}{{/manufacturer}} )
{{/if}}
```

To be able to do this and separately accessing the model, I'd need to know the template, process it and access the model for `color`, `description` and `manufacturer` *if* they were used in the template. Doing it that way would require a full (separate) handlebars parser to return the values.

As you can see above, based on the example context, "description" is never used. The template is what defines which variables get used, not the model. Doing this manually means we'd have to write a class just to match which variables the template used.

Based on the template, the params that were meant to be outputted (but were replaced with "?") are `[ color[0], color[1], manufacturer[0] ]`

Here's what I *want* to provide if I were to run that previous template:
getQuery(): `...WHERE color IN (?, ?) AND manufacturer IN (?)`
getParams(): `[ color[0], color[1], manufacturer[0] ]` which is actually `[ "black", "silver", "Samsung" ]`

**Comment by jknack** [comment]
hmm ok, i see now. One solution will be to create a custom ValueResolver

At very high level should be something on these lines:

```java

class ForwardingVR implements ValueResolver {
 
 // instance var for collecting params
  private List<Object> params = ...

  public ForwardingVR(ValueResolver delegate) {
    this.delegate = delegate;
  }
  
  public Object resolve(Object context) {
     Object resolved = delegate.resolve(context);
    if (resolved != UNRESOLVED)  {
      params.add(resolved);
      return "?";
    }
   return resolved;
   }

  ...
}

```

So, your custom vr should delegate the resolution to any of the existing value resolvers. Then every time you got a resolved value, just return the ```?```  and save the value in an instance var.

You need to make sure you create a new VR per invocation, bc your VR wont be thread safe bc of the params var. See next example:

```
ForwardingVR vr = new ForwardingVR(delegate);
Context context = new Context.Builder().resolver(vr).build();
template.apply(context);

// access to params
vr.params
```

Is this what do you need? (more or less)

**Comment by joshq00** [comment]
Yes, something like this is what I'm looking for - but, with this implementation, doing {{#if color}} "color" be added to the params, correct?

Using a helper I can do it, but I'd like to automate that. Here's my "~working" example:
```java
handlebars.registerHelper("param", new Helper<Object>() {
	public CharSequence apply(Object context, Options options) throws IOException {
		params.add( context );
		return "?";
	}
});
```

but I have to use `{{param .}}` or `{{param color}}` and would like to automate every time {{.}} or {{color}} or etc are used

**Comment by jknack** [comment]
yea, you're right it won't work. what you did is good, but I get your point.

yea there is no easy way of doing this :(

**Comment by joshq00** [comment]
Is there some way I can hook in between the resolver and the escaper? If it reaches the escaper, it should be added to the list, but I need the value before it gets converted to a charsequence.

Only other thought is to do some kind of ugly `replace( "{{(...)}}", "{{param $1}}" )`

**Comment by jknack** [comment]
No there is no way, but there is probably one other way (didn't try it).

1. create a new value resolver, delegate resolution to a another vr (as before)
2. your new value resolver should return a instance of ```com.github.jknack.handlebars.Lambda``` (a concept inherited from Mustache)
3. the lambda you hold a ref to the resolved value: ```new PreparedStatementHook(value);```

The lambda looks like:

```java

Object value;

public String apply(Context context, Template template) {
   params.add(value);
   return "?";
}
```

As I said, didn't try it but think that should work, just be careful with the params var and multithreading.

Let me know if that works

**Comment by jknack** [comment]
Closing the issue. But next release will have a value formatter, still not sure if that helps or not. See #364

**Comment by joshq00** [comment]
Hey @jknack, sorry I never replied to this.

What I ended up doing was just creating a class that, when called, creates a new HandleBars instance, registers the `{{param ...}}` helper (plus some others, like `{{in ...}}`, `{{like ...}}`, etc) and returns a `Result` object.

The result object has `String getQuery()` and `Collection < Object > getInputs()` - which get populated by those helpers / the handlebars output.

It's not as ideal as I'd like - but at least it's encapsulated, so... shrug.

I realized that automatically turning every {{.}} into ? might not be best, anyhow. For example, if we make the SELECT fields dynamic, those can't be prepared inputs... So we'd have to go this route, anyhow

**Comment by joshq00** [comment]
PS : I didn't want to load the templates for every query that is run, but using the Guava cache cached the inputs (my helpers never got called! bahhh)

This may be useful to others who want the parser to fully execute every time, but don't want all the IO

```java
public class CachingFileLoader extends ClassPathTemplateLoader {
	private Map< String, String > templateMap = new HashMap<>();

	@Override
	public String resolve(String uri) {
		if ( templateMap.get( uri ) == null ) {
			templateMap.put( uri, super.resolve( uri ) );
		}
		return templateMap.get( uri );
	}
}
```
