### ISSUE TITLE
what handlebars.java can do and what differences between handlebars.java and handlebars.js

### ISSUE THREAD

**Issue by ruqing** [jknack/handlebars.java#346]
hi jknack,
    I'm a novice at handlebars.java.I know handlebars.js is a js framwork but don't know what is handlebars.java.So I want to know what can handlebars.java do and what's the connection between it and handlebars.js. I have no choice to ask you for help  cause there is few information about it on the Internet.If bring you inconvenience, please forgive me

**Comment by jknack** [comment]
handlebars.java is a server side template engine (like freemarker, velocity, etc..)

Template syntax is driven by the Mustache Spec: https://mustache.github.io/ but also http://handlebarsjs.com/. Latest, extend the Mustache Spec.

That's all handlebars.java is about, just a template engine for Java.

Now, if your app does a lot of JavaScript or MVC on the browser... people usually choose a template engine for the browser: handlebars.js (mustache.js, jade, haml, etc...)

On such apps, handlebars.java let's you use/reuse templates in the server and browser. This is the main goal of handlebars.java: "reuse the templates". Here there aren't so much difference the same template works at server side (handlebars.java) and/or client side (handlebars.js). I documented some minor diff here: https://github.com/jknack/handlebars.java#differences-between-handlebarsjava-and-handlebarsjs

Another issue that people want to solved too "is to reuse the helpers" again at server and client sides. This one is more tricky and handlebars.java does something on this point but it not always work.
What does it? It let you define your helpers in javascript and being executed in Java through Rhino.
This feature works good most of the times, but not always.

Hope this help and you will find more info at:

http://jknack.github.io/handlebars.java/meeting.html
http://jknack.github.io/handlebars.java/reuse.html

**Comment by ruqing** [comment]
Thank you very much for your solution  and I'm very sorry not reply in  time.
After your answer and repeated study the documents, I create a new Java Web project and import handlebars.jar,handlebars-springmvc.jar.Now I can use these labels like {{}} in my pages but not enough. I haven't felt what is template yet.In company ,the project I'm doing was also used handlebars and that's the reason I study it.In our pages,every  module have view.js,view.css,view.hbs.For example,there is a login folder and only view.js,view.css,view.hbs in it.As long as the controller  returns '/login' ,it can find the page.I found handlebars-proto may implement,so I import it and do follow the documents but can't implement.
Now I have two questions:
First,what time handlebars-proto will be used.I found it's a server.As known,the java web project often used tomcat,jetty and so on as the server.
Next, how to implement the pages of the project  I'm doing,only handlebars can do it or what technology you know  could implement it.
Last,I come from China and my English is very poor.
If my description is not clear,please forgive my words not accurate enough,I‘ll try.
Thanks again.
