### ISSUE TITLE
handlebars 3.0 support

### ISSUE THREAD

**Issue by mattkime** [jknack/handlebars.java#349]
changes are outlined here - https://github.com/wycats/handlebars.js/blob/master/release-notes.md#v300---february-10th-2015

additional template features are of particular interest.

**Comment by husayt** [comment]
Does anyone know if handlebars 3 already supported? If we just switch js library to handlebars,js 3 will it work?

**Comment by mattkime** [comment]
the handlebars js file is only used for hbs -> js compilation. rendering of templates uses java

**Comment by grnadav** [comment]
@mattkime I didn't understand from your reply whether it's supported or not. 
Can one just set 
handlebars.handlebarsJsFile("/handlebars-v3.0.0.js"); 
and expect it to work?

**Comment by mattkime** [comment]
@grnadav if you're using handlebars.java to render hbs templates then that code won't change a thing. the js file is only used to compile hbs files into javascript. this is useful when rendering hbs on the client as its faster and doesn't require the full handlebars.js functionality.

**Comment by grnadav** [comment]
@mattkime Got it. Thanks!

**Comment by jknack** [comment]
Guys,

 I will release a 2.1.0 tomorrow, but partials params support #350 & #357.

But sure what else is new in terms of language feature, so do me a favor and open new issues describing what else need to be done to create a 3.0.0 compatible version.

For now, I will close this issue bc it is too vague.

Thanks

**Comment by husayt** [comment]
Thanks for latest updates @jknack .

As for handlebars 3, the latest is 3.0.2. 

In terms of new feature there from version 2 I can see these: 

* [#941](https://github.com/wycats/handlebars.js/pull/941) - Add support for dynamic partial names
* [#892](https://github.com/wycats/handlebars.js/pull/892)  -  Chained else blocks
* [#910](https://github.com/wycats/handlebars.js/issues/910)  - @last and other each changes
* [#805](https://github.com/wycats/handlebars.js/issues/805)  -  Strict Mode
* [#886](https://github.com/wycats/handlebars.js/issues/886) - Add SafeString to context (or use duck-typing) 
* [#887](https://github.com/wycats/handlebars.js/issues/887)  - Handlebars.noConflict() option?
* [#]()  - @data methods can now have helper parameters passed to them
* [#906](https://github.com/wycats/handlebars.js/pull/906)  -  Block Params
* [#940](https://github.com/wycats/handlebars.js/pull/940),  [#964](https://github.com/wycats/handlebars.js/pull/964)  - Add missing reserved words so compiler knows to use array syntax:

I am not sure which of these are already supported. Some of them might not even make sense for Java environment.

As hbs.js is evolving it will be difficult to maintain 1-1 compatibility. To maintain compatibility with hbs.js as it develops it might help to be able to run hbs.js unit tests from hbs-java.

Here is a full release notes for hbs.js:
https://github.com/wycats/handlebars.js/blob/master/release-notes.md

Again thanks for great work, it is very appreciated.
