### ISSUE TITLE
Partials with parameters

### ISSUE THREAD

**Issue by karlhorky** [jknack/handlebars.java#350]
Can you support the handlebars.js partial parameters notation? Like in the spec [here](https://github.com/wycats/handlebars.js/blob/e290ec24f131f89ddf2c6aeb707a4884d41c3c6d/spec/partials.js#L26-L32)?

*context*
```json
{
  "title": "profile",
  "dudes": [
    {
      "name": "Yehuda",
      "url": "http://yehuda"
    },
    {
      "name": "Alan",
      "url": "http://alan"
    }
  ]
}
```

*index.hbs*
```hbs
<ul>
  {{#each dudes}}
    {{> dude title=../title class="list-item"}}
  {{/each}}
</ul>
```

*dude.hbs*
```hbs
<li class="{{class}}">
  {{title}}: <a href="{{url}}">{{name}}</a>
</li>
```

*expected output*
```html
<ul>
  <li class="list-item">
    profile: <a href="http://yehuda">Yehuda</a>
  </li>
  <li class="list-item">
    profile: <a href="http://alan">Alan</a>
  </li>
</ul>
```

I saw the `#partial` and `#block` helpers [here](https://github.com/jknack/handlebars.java/commit/61fea24059b19507ea91d167bd988582a50b2c4c), but I'm working on a project where we would like to keep parity with handlebars.js if possible.

**Comment by husayt** [comment]
Seems this card needs to be merged with 
https://github.com/jknack/handlebars.java/issues/349

**Comment by karlhorky** [comment]
@husayt These partials were actually implemented in v2.0.0. So this is a bit older than v3.0.0 as in the other issue.

**Comment by digitor** [comment]
Has this been implemented? This feature is pretty useful.

**Comment by digitor** [comment]
Could this be the culprit?
Says it's using "/handlebars-v1.3.0.js"
https://github.com/jknack/handlebars.java/blob/master/handlebars/src/main/java/com/github/jknack/handlebars/Handlebars.java#L337

**Comment by karlhorky** [comment]
Thanks @jknack!

**Comment by felegy-norbert** [comment]
HI,
I am using the version 2.2.2 together with handlebars-v2.0, and I cannot get this parameter and partial thing working.

I have a very simple use case where:

{{> mypartial label="Value of the label" }}

 mypartial.hbs.html
{{label}}

And it is not working. Do you see any problem with it? Also, can someone show me a working example?
Thank you.

**Comment by jknack** [comment]
did you see any error? there are a few unit tests that demonstrate partials param in action. Here is one: https://github.com/jknack/handlebars.java/blob/master/handlebars/src/test/java/com/github/jknack/handlebars/i350/Issue350.java

**Comment by keesvandieren** [comment]
Partial parameters require the MapValueResolver.INSTANCE to be registered as resolver in the context. If partial parameters are not passed, this might be the reason.
