### ISSUE TITLE
Question: Implementing A Falsey String

### ISSUE THREAD

**Issue by LTheobald** [jknack/handlebars.java#353]
One of the problem I have with Handlebars.Java is that the strings `"false"` doesn't result in a falsey value.  So for example:

    {{#if "false"}}
      Hello!
    {{/if}}

Would always print something. Not a bad thing on it's own but add this to the fact that all Helper's want you to return a `CharSequence` then it's very hard to write a helper that you can use in a true/false situation. I'll have a dive through the code in a minute to see where this is setup & possibly implement a fix for a pull request.

But would this be an issue? Does it go against the Moustache spec (from what I've seen, it can be left up to the implementing language)? Are there any other problems that would make this a bad idea?

**Comment by LTheobald** [comment]
Having a look at the code, I can see that I can write a helper that would return the values `"true"` or `""` for the desired effect. I guess I just don't find it very intuitive :( It also means my code would have to completely forgo using boolean values and I'd have lots of...

    return ifTestThatReturnsBoolean() ? "true" : "";

At the end of my helpers.  I may throw a pull request in where the `Options` class has an option to turn on a 'relaxed' mode. That in turn would alter the `isFalsey()` method to call a `isEmpty` check that considers more things to be falsey

**Comment by jknack** [comment]
probably I'm missing something but the output of a helper is usually printed out in the final output, that's way helpers return a char sequence.

then you assert ```if/unless/etc``` against data from model, where data can be a ```boolean```


also, not sure what do you mean with "false" to be a falsey value. In JS, the string "false" isn't a falsey value, just the "" (empty) string

**Comment by LTheobald** [comment]
No, you're not missing something - I was! I'm still new to Handlebars & wasn't 100% sure when you should & shouldn't use helpers & this clears it up for me.  Cheers.
