### ISSUE TITLE
New release or public snapshot builds?

### ISSUE THREAD

**Issue by GrahamDennis** [jknack/handlebars.java#354]
The last release was at the end of November 24, and I'd really like to use the new @index_1 in the each helper.  Can you do a release or create publish snapshot builds as described in the README?  The last SNAPSHOT build is from October last year.

**Comment by jknack** [comment]
snapshot build is up to date now.

**Comment by GrahamDennis** [comment]
Thanks @jknack!  Feel free to close this out.  A release sometime would be awesome too, but I can live with a snapshot.
