### ISSUE TITLE
Cannot numberFormat "0.0"

### ISSUE THREAD

**Issue by xtopolis** [jknack/handlebars.java#355]
Issue: Providing "0" or "0.0" as an argument for numberFormat does not return a number
Found in 1.3.0, and likely persists in 2.0.

example:
```{{numberFormat "0.0"}}```
```{{numberFormat "0.0" "currency"}}```

/master/handlebars/src/main/java/com/github/jknack/handlebars/helper/StringHelpers.java
Starting at line 690:

  ```@Override
  public CharSequence apply(final Object context, final Options options) throws IOException {
    if (options.isFalsy(context)) {
```

Somewhere in there through Handlebars.java (Utils.isEmpty) it evaluates to false for the "0.0" argument, and ends up returning the first options, such as "currency."

Shouldn't it be able to numberFormat 0.0, or is there a different way this should be used?
Thank you.

**Comment by gsastry** [comment]
:+1: 

The issue is here: 

stringhelpers:apply:690
```java
public CharSequence apply(final Object context, final Options options) throws IOException {
  if (options.isFalsy(context)) {
    Object param = options.param(0, null);
    return param == null ? null : param.toString();
  }
  return safeApply(context, options);
}
```
0 is falsy so price=0
{{numberFormat price 'currency'}} returns "currency" instead of running it and getting "$0.00"
