### ISSUE TITLE
Jackson2Helper Escaping

### ISSUE THREAD

**Issue by stevelaw** [jknack/handlebars.java#358]
When using the Jackson2Helper the resulting string contains escape characters such as `\n` and `\t`, and quotes are escaped as well.

It doesn't appear that it is possible to disable this behavior.  I believe this is due to the `SafeString` being called here: https://github.com/jknack/handlebars.java/blob/master/handlebars-jackson2/src/main/java/com/github/jknack/handlebars/Jackson2Helper.java#L209

It would be nice to be able to disable this in some cases.

**Comment by jknack** [comment]
no, has nothing to do with SafeString. This is how JSON got escape it and is done via Jackson
