### ISSUE TITLE
Support triple custom delimiters to unescape a variable, just as `{{{ variable }}}` unescapes the variable

### ISSUE THREAD

**Issue by gsastry** [jknack/handlebars.java#362]
`{{{ variable }}}` unescapes `variable`. It'd be great we could have the same functionality for custom delimiters (e.g. `[[`). For example, `[[[ variable ]]]` should unescape `variable`, and we shouldn't have to do `[[ & variable ]]`.

Let me know your thoughts, thanks.

**Comment by jknack** [comment]
like the idea but it wont work on delimiters like ```${ }``` or ```<% %>```.

also, this isn't part of the mustache spec and it won't work on handlebar.js
