### ISSUE TITLE
Add variable formatter

### ISSUE THREAD

**Issue by jknack** [jknack/handlebars.java#364]
Format variable expression somehow. Usage:

```java
handlebars.with(new Formatter() {
      @Override
      public Object format(final Object value, final Chain next) {
        if (value instanceof Date) {
          return ((Date) value).getTime();
        }
        return next.format(value);
      }

});
```

If now is a Date:

```
{{now}}
```

It will print epoch millis since Jan 1 1970 (.getTime())

A formatter should format a variable or call the next formatter in the chain when isn;'t possible.

**Comment by jknack** [comment]
See commit: https://github.com/jknack/handlebars.java/commit/66206701521f694a2c7a751d98f1acd66b3bb768

**Comment by joshq00** [comment]
This will be very useful
