### ISSUE TITLE
When building handlebars-java/handlebars, the tests fail with any test regarding the starting /

### ISSUE THREAD

**Issue by AnthonyClink** [jknack/handlebars.java#366]
I am simply building from maven and I may be either missing a dependency or am missing a goal...

from handlebars-java/

    mvn clean install

Tests in error:
    ClassPathTemplateLoaderTest.setBasePathWithDashDash:77 » FileNotFound /mustach...
    ClassPathTemplateLoaderTest.subFolder:49 » FileNotFound /mustache/specs/commen...
    ClassPathTemplateLoaderTest.setBasePath:70 » FileNotFound /mustache/specs/comm...
    ClassPathTemplateLoaderTest.subFolderwithDashAtBeginning:57 » FileNotFound /mu...
    FileTemplateLoaderTest.setBasePathWithDash:79 » IllegalArgument File not found...
    FileTemplateLoaderTest.subFolder:50 » FileNotFound src\test\resources/mustache...
    FileTemplateLoaderTest.setBasePath:71 » IllegalArgument File not found: src\te...
    FileTemplateLoaderTest.subFolderwithDashAtBeginning:58 » FileNotFound src\test...
    ServletContextTemplateLoaderTest.setBasePathWithDash:99 » FileNotFound /commen...
    ServletContextTemplateLoaderTest.subFolder:44 » FileNotFound /mustache/specs/c...
    ServletContextTemplateLoaderTest.setBasePath:85 » FileNotFound /comments.yml
    ServletContextTemplateLoaderTest.subFolderwithDashAtBeginning:58 » FileNotFound
    CommentsTest.data:33->SpecTest.data:106->SpecTest.data:126 » FileNotFound File...
    DelimitersTest.data:33->SpecTest.data:106->SpecTest.data:126 » FileNotFound Fi...
    InterpolationTest.data:33->SpecTest.data:106->SpecTest.data:126 » FileNotFound
    InvertedTest.data:33->SpecTest.data:106->SpecTest.data:126 » FileNotFound File...
    LambdasTest.data:148->SpecTest.data:106->SpecTest.data:126 » FileNotFound File...
    PartialsTest.data:67->SpecTest.data:106->SpecTest.data:126 » FileNotFound File...
    SectionsTest.data:33->SpecTest.data:106->SpecTest.data:126 » FileNotFound File..  .

   [INFO] ------------------------------------------------------------------------
   [INFO] Reactor Summary:
   [INFO]
   [INFO] Handlebars.java .................................... SUCCESS [  1.238 s]
   [INFO] Handlebars ......................................... FAILURE [ 17.350 s]
   [INFO] Handlebars Helpers ................................. SKIPPED
   [INFO] Handlebars Spring MVC .............................. SKIPPED
   [INFO] A Jackson 1.x helper ............................... SKIPPED
   [INFO] A Jackson 2.x helper ............................... SKIPPED
   [INFO] A Markdown Helper .................................. SKIPPED
   [INFO] Humanize helpers ................................... SKIPPED
   [INFO] A standalone Handlebars Server ..................... SKIPPED
   [INFO] Handlebars Guava Cache ............................. SKIPPED   
   [INFO] Handlebars.js maven plugin ......................... SKIPPED
   [INFO] Handlebars.js maven plugin tests ................... SKIPPED
   [INFO] Handlebars.java integration tests .................. SKIPPED
   [INFO] Handlebars.java without Rhino ...................... SKIPPED

**Comment by jknack** [comment]
mustache spec are outside handlebars.java repository. in order to compile the project you need to initialize git submodules: http://git-scm.com/book/en/v2/Git-Tools-Submodules
