### ISSUE TITLE
single quote escape

### ISSUE THREAD

**Issue by zsoltszloboda** [jknack/handlebars.java#370]
Utils.escapeExpression() does NOT escape the single-quote character (x27), which SHOULD be escaped, I think.
However, it escapes the grave accent (x60) character, which is unnecessary, I think.
Check this: https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet

**Comment by jknack** [comment]
It does: https://github.com/jknack/handlebars.java/blob/master/handlebars/src/main/java/com/github/jknack/handlebars/Handlebars.java#L246-L248

**Comment by zsoltszloboda** [comment]
But why does it escape the grave accent (x60) character?

**Comment by jknack** [comment]
default escape strategy works as in handlebars.js, see https://github.com/wycats/handlebars.js/blob/972f52171878ce88af455d7e8fac401a27ba0168/lib/handlebars/utils.js

it is done this way to be 100% compatible with handlebars.js

if you need a different escape function you can try:

```java
hbs = new Handlebars().with(new MyEscapeStrategy());
```
