### ISSUE TITLE
@first not effective for guava ImmutableList ( impl of java.util.List )

### ISSUE THREAD

**Issue by frko** [jknack/handlebars.java#371]
<ul class="fleft clear_fix">
                {{#each menuLinks}}
                    <li {{#if @first}}class="first"{{/if}}><a href="{{href}}">{{title}}</a></li>
                {{/each}}
            </ul>

@first is never evaluated as true and therefore class="first" is never printed

**Comment by frko** [comment]
Bumping as no reply has been placed yet. Basic functionality unfortunately isnt working but often used throughout many projects.

**Comment by jknack** [comment]
can't reproduce it: https://gist.github.com/jknack/e9f77cd3b35a18be3072
