### ISSUE TITLE
about the Handlebars.java Server

### ISSUE THREAD

**Issue by aj4g** [jknack/handlebars.java#372]
Hi Edgar,

Thank you for providing us the Handlebars.java server,
I want to do some development based on it, Is it a open-source project?

**Comment by jknack** [comment]
sure dude!

https://github.com/jknack/handlebars.java/tree/master/handlebars-proto

but it is very very simply, if you need a bit more and still keep simplicity, you might want to try my web server: http://jooby.org

**Comment by aj4g** [comment]
thank you, you are so kind!

In China,  java8 is rarely used in the production environment,  we like java7 more,
because there is  a wall between china and outside, 囧

I will use handlebars-proto as a test server in handlebars front-end developing. it is really good.

(please forgive my poor English...)
