### ISSUE TITLE
Dynamic Partials

### ISSUE THREAD

**Issue by karlhorky** [jknack/handlebars.java#375]
As mentioned in [#349](https://github.com/jknack/handlebars.java/issues/349#issuecomment-96656927), dynamic partials were added to Handlebars.js in wycats/handlebars.js#941. They [are invoked using the following syntax](http://handlebarsjs.com/partials.html#dynamic-partials).

```hbs
{{> (partialNameHelper) }}
```

In order to use context variables, Handlebars.js uses [the lookup helper](http://handlebarsjs.com/builtin_helpers.html#lookup) like this:

```hbs
{{> (lookup . 'myVariable') }}
```

However, the [stringFormat helper](https://github.com/jknack/handlebars.java/blob/0aeaf49a4ccef044aa1030a47109f3f28c31f15f/handlebars/src/main/java/com/github/jknack/handlebars/helper/StringHelpers.java#L333-L353) looks like a viable alternative in Handlebars.java:

```hbs
{{> (stringFormat "%s" myVariable) }}
```

**Comment by karlhorky** [comment]
Updated - the stringFormat helper can probably be used instead of a new lookup helper.

**Comment by jknack** [comment]
Hi @karlhorky 

I'm sorry but don't get how the lookup helper works and what impact it has inside the dynamic partial. Can you add an example?

Thanks

**Comment by karlhorky** [comment]
Updated the original post again with an example of their lookup helper.

**Comment by karlhorky** [comment]
But I think the `stringFormat` helper should work in Handlebars.java projects.

**Comment by karlhorky** [comment]
Thanks @jknack!

**Comment by jknack** [comment]
no problem and thank you for helping me to identify missing features of handlebars.java vs handlebars.js

I will push to maven central today, but I'm sure new release will be available tomorrow.

**Comment by karlhorky** [comment]
Glad to help :)

**Comment by jknack** [comment]
@karlhorky in the next few days, I'm going to release 3.0.0 is there any other pending js feature that we are missing? (compared to handlebarsjs 3.0.0) 

thanks

**Comment by karlhorky** [comment]
Actually, from our side, I haven't needed anything that's missing since Handlebars.java `2.2.0` was released.

Maybe anything else to be found here?
https://github.com/wycats/handlebars.js/blob/master/release-notes.md

Thanks for your hard work!

**Comment by karlhorky** [comment]
Also check a bit earlier in the release notes - one of my issues was actually about a feature introduced in Handlebars.js `2.0.0` if I recall correctly.

**Comment by andreavaghi** [comment]
I don't get how i can use Dynamic Partials with Handlebars.java.

i've tried 
```
{{> (dinamycPartial) }}
```
and
```
{{> (lookup '.' 'dinamycPartial') }}
```
where `dynamicPartial` is a String with the name of the template (es. "partials/test"), but it isn't working
i'm using 2.2.0

**Comment by jknack** [comment]
here are some unit test that might help: https://github.com/jknack/handlebars.java/blob/master/handlebars/src/test/java/com/github/jknack/handlebars/i375/Issue375.java

also, make sure you don't have a ```typo```: ```dinamycPartial``` vs ```dynamicPartial```

**Comment by andreavaghi** [comment]
fortunately it was only a typo in the question!
looking at the test i've resolved with `{{> (lookup . 'dynamicPartial' }}`, removing the quotes around the dot

thank you for the really quick help
