### ISSUE TITLE
this.property not resolved in some cases in new build

### ISSUE THREAD

**Issue by dontgitit** [jknack/handlebars.java#376]
Hey, 

We upgraded to handlebars 2.1 after using 1.x and noticed a discrepancy in behavior that seems like a bug. Specifically, given the following json:

```json
{
  "foo": [
      {
        "price": 5
      },
      {
        "price": 7
      }
    ]
}
```

This works:
```handlebars
{{#each foo}}
  {{#if this.price}}{{numberFormat price 'currency'}}{{/if}}
  <br/>
{{/each}}
```

outputs 
```
$5.00
$7.00
```

While this doesn't:
```handlebars
{{#each foo}}
  {{#if this.price}}{{numberFormat this.price 'currency'}}{{/if}} 
  <br/>
{{/each}}
```

outputs
```
currency
currency
```

The only difference is ```price``` vs ```this.price``` inside the ```numberFormat```

Is this a bug or intended behavior?

**Comment by jknack** [comment]
It is bug, introduced in 2.0.0 a consequence of https://github.com/jknack/handlebars.java/issues/329

I need to revert that change soon than later
