### ISSUE TITLE
not able to compile handlerbar templates with : in JSON properties name [handlebars-maven-plugin]

### ISSUE THREAD

**Issue by sharmalalit** [jknack/handlebars.java#379]
Consider my template is :
<div> [a:b] </div>
i.e. json propery has key  "a:b"
I am not able to compile such templates with this plugin.

plugin does not supports "segment-literal notation, [ "
http://handlebarsjs.com/expressions.html

**Comment by AnthonyClink** [comment]
have you tried "a:b":"value"?

**Comment by jknack** [comment]
I can't reproduce it, see https://github.com/jknack/handlebars.java/commit/0c67579e77229f962cc8c2beab2f386b83c4581d
