### ISSUE TITLE
FileTemplateLoader can be slow for production where files don't change.

### ISSUE THREAD

**Issue by agentgt** [jknack/handlebars.java#380]
While porting handlebars over to this benchmark: https://github.com/agentgt/template-engine-benchmarks I noticed that the file loading template loader does unnecessary file exist checks. This is in part because the caching of templates is sort of in the wrong place or at least misleading. This is because TemplateSource for file has to check if the file exists.

You can see the benchmark code with comments here: https://github.com/agentgt/template-engine-benchmarks/blob/master/src/teb/HandlebarsBenchmark.java

You can run the tests like:

```
$ ant handlebars
Buildfile: /Users/agent/projects/template-engine-benchmarks/build.xml

init:

compile:

handlebars:
     [java] ntimes: 10000, real time: 2364(msec)

BUILD SUCCESSFUL
Total time: 3 seconds
```

Using the default file template loader its about 1/3 slower.

```
$ ant handlebars -Dhandlebars.defaultTemplateLoader=true
Buildfile: /Users/agent/projects/template-engine-benchmarks/build.xml

init:

compile:

handlebars:
     [java] ntimes: 10000, real time: 3042(msec)

BUILD SUCCESSFUL
Total time: 4 seconds
```

BTW you can see the results of the test compared to other frameworks in Travis:
https://travis-ci.org/agentgt/template-engine-benchmarks

**Comment by jknack** [comment]
cool!, can you fix it? and send a pull request?

**Comment by agentgt** [comment]
I think the easiest thing to do is to either make the FileTemplateLoader configurable to not always check or we make a new subclass CachedFileTemplateLoader.

I'll assume new subclass and do a pull request with a simple ConcurrentHashMap (that might need to be abstracted out also).

In my own projects this is less of an issue as I hang on to the compiled `Template` and cache that instead but I was trying to follow the Mustache benchmark code wise (ie calling compile all the time).

**Comment by agentgt** [comment]
Actually it looks like the best thing would be to take advantage of the `WatchService` in JDK 7 which unfortunately would make Handlebars require JDK7 (instead of 6).

I think the best thing is to close this issue and make a separate micro project since TemplateLoader is pluggable and nothing is really broken (just less efficient).

**Comment by jknack** [comment]
I misunderstood the problem... but yea in prod you should use one of the available handlebars.java cache.

Without cache (dev?) was done in the way it was: intentionally. In dev, in my experience it is better to check if there is any code change and/or just reload than adding a thread to watch or watching service (too expensive!).

**Comment by agentgt** [comment]
Just to clarify...

If you call `Handlebars.compile(...)` on every single request it will be slow as shown in the benchmarks because `TemplateSource` has to create a URL and check if the file exists. 

The ideal cache is not `Map<TemplateSource,Template>` but rather `Map<String,Template>` (I'm just using `Map` to mean cache). Creating the key (`TemplateSource`) is expensive in the current implementation. Just to be clear again ... the handlebars.java current caches will not fix this problem (calling `compile` all the time). The current caches obviously speed things up but they are not ideal as shown by the benchmark code.

Luckily Spring MVC handlebars and probably others implement their own cache and hold on to the compiled `Template` (or at least my own version does).
