### ISSUE TITLE
Is possible with handlebars.java to pull in templates in a WebApp externally?

### ISSUE THREAD

**Issue by peterpilgrim** [jknack/handlebars.java#382]
Hi 

I am investigating the Handlebars.java with a new framework called Java EE MVC 1.0 (Ozark).

Is possible with Handlers.java to pull in a partial from view location in a Java EE web application?

Suppose I have 

```
src/main/webapp/header.hbs
src/main/webapp/footer.hbs
src/main/webapp/person.hbs
```   

And person.hbs is defined as

```
<!DOCTYPE html>
<html>
<head lang="en"> ...
</head>
<body>
    {{> header}}
    <div class="other-content">
        <h1>Person</h1>
        <div> <p class="lead"> {{person.firstName}} </p></div>
        <div> <p class="lead"> {{person.lastName}} </p></div>
        <div> <p class="lead"> {{person.age}} </p></div>
    </div>
    {{> footer}}
</body>
</html>
```

and header.hbs is defined as

```
<h1>{{title}}</h1>
```

and  footer.hbs is defined as

```
<span>Powered by Handlebars Java</span>
```

In the Handlerbar.js you need to register templates, in the Java world, I think this default configuration should be possible.

How do I achieve this configuration with Handlebars.java?

TIA

**Comment by peterpilgrim** [comment]
Found the answer by searching and RTFM! 

No worries.

```
            final TemplateLoader loader = new ServletContextTemplateLoader(servletContext);
            final Handlebars handlebars = new Handlebars(loader);
            final Template template = handlebars.compileInline(viewContent);
            template.apply(models, writer);
```
Closing this one.

**Comment by jknack** [comment]
sorry, I saw your question and then forgot to answer. But, I'm glad you figure it out :)
