### ISSUE TITLE
maven version 3.3.1 can not resolve dependencies

### ISSUE THREAD

**Issue by breneser** [jknack/handlebars.java#384]
I am using handlebars-java 2.2.0 for my project. And dependencies are as below. The problem is , using a maven version later than 3.0.5, when building I get the warnings below. 

    [WARNING] The POM for com.github.jknack:handlebars:jar:2.2.0 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
    [WARNING] The POM for com.github.jknack:handlebars-jackson2:jar:2.2.0 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
    [WARNING] The POM for com.github.jknack:handlebars-markdown:jar:2.2.0 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
    [WARNING] The POM for com.github.jknack:handlebars-humanize:jar:2.2.0 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details

And when the app is running i get  java.lang.ClassNotFoundException: org.antlr.v4.runtime.TokenSource   or with some versions of maven ( I think it was 3.1  )  I get java.lang.ClassNotFoundException: org.antlr.v4.runtime.CharStream

    
		<dependency>
			<groupId>com.github.jknack</groupId>
			<artifactId>handlebars</artifactId>
			<version>${handlebars-java-version}</version>
		</dependency>

		<dependency>
			<groupId>com.github.jknack</groupId>
			<artifactId>handlebars-jackson2</artifactId>
			<version>${handlebars-java-version}</version>
		</dependency>

		<dependency>
			<groupId>com.github.jknack</groupId>
			<artifactId>handlebars-markdown</artifactId>
			<version>${handlebars-java-version}</version>
		</dependency>

		<dependency>
			<groupId>com.github.jknack</groupId>
			<artifactId>handlebars-humanize</artifactId>
			<version>${handlebars-java-version}</version>
		</dependency>

**Comment by jknack** [comment]
odd, but I'm sure you have corrupted files in your local maven repository. Delete them locally and try again. I didn't found any issue with maven 3 and handlebars 2.2.0.

**Comment by breneser** [comment]
I actually deleted them all, and tried again with no luck. Transitive dependencies are not resolved for any of the handlebars-java artifacts. I tried to deploy to Heroku, same problem on Heroku as well.

**Comment by breneser** [comment]
Sorry about this. I have been using jitpack.io to include some dependencies. Seems like it picks handlebars-java submodules from Github and builds them. 

Since the parent project is not there, it probably fails building it and that's why I can't get the dependencies.

**Comment by akpmp** [comment]
Hi
i have got transitive dependency on sciknowmineProject using maven3. how to resolve it.

Thanks
