### ISSUE TITLE
Needed aggregate hbss template before compilation

### ISSUE THREAD

**Issue by ssharma1234** [jknack/handlebars.java#387]
Hi,
We have a requirement where we want to merge the inline template in the parent template before proceeding for the  parent template compilation in Java using handlebar.compile(TemplateSource).
We want to store the complete compiled template in cache for further processing.

Scenario 
We have a carousel template like 

```
{{#each carousel.slides}}
    {{#if panel.image}} image {{else}} video {{/if}}
        {{#if panel.image}}
            {{include this "panel/displayAs_imagePanel.hbss" }}
        {{else}}
            {{include this "panel/displayAs_videoPanel.hbss" }}
        {{/if}}  
{{/each}}
```

inside the template we are having a inline Helper  as      {{include this "panel/displayAs_imagePanel.hbss" }}

We want merge or embedded the 'panel/displayAs_imagePanel.hbss' inside parent template before compiling.

**Comment by mattkime** [comment]
why do you need to do this?
