### ISSUE TITLE
Question: Passing the current context to included partials?

### ISSUE THREAD

**Issue by pawandubey** [jknack/handlebars.java#388]
I have a template `head` as:
`<p>Title: {{config.title}}</p>`

And I am including it in `index` as:
````
{{>head}}
<p>{{config.title}}</p>
````
With `config.title` set to `My Title`.

The content is rendered as:
````
Title:
My Title
````

I tried passing the current context to the partial as `{{>head this}}` but this made no difference. Any guide how to accomplish this?

**Comment by pawandubey** [comment]
Ah, never mind. Got it. :)

**Comment by abutterworth** [comment]
What was your solution? I'm running into a similar problem.

**Comment by abutterworth** [comment]
Maybe not what you ended up doing, but for other's reference you can access the root context like this:
@root.myVar  
http://stackoverflow.com/questions/17364897/access-to-root-context-in-handlebar-js-template

**Comment by pawandubey** [comment]
@abutterworth I passed it like this `{{>head this}}

**Comment by jknack** [comment]
Guys,

 You don't need anything special in handlebars.java. The Mustache Spec said that a partial has access to the current context, so: ```{{> head}}``` and ```{{> head this}}``` are identical.
