### ISSUE TITLE
Question: Any way to inspect the in memory representation of a template?

### ISSUE THREAD

**Issue by khoubyari** [jknack/handlebars.java#389]
Is there any way for me to programmatically get a list of the variable names inside a template?

For example, if the template it 
 ```
{{#items}}
<li>{{name}} is {{color}}</li>
{{/items}}
{{reportDate}}
```

then the API would return a list of strings (or map of some sort) like:
```
"items.name",
"items.color",
"reportDate"
```

Alternatively, is there a way to declare a callback for evaluating each variable. For example if the engine gets to a point to evaluate {{address}} it would call *my* callback function to get the value to bind to "address".

The use case is we want to create a utility for the user to create the template at runtime but NOT have to create the json input file for it... instead our frameworks wants to build that json (with data in the database) automatically and provide it to the handlebar engine. We could potentially do this if we write (or use) a handlebar parser for the templates but just wondering if there are any API hooks we can use to get at the list of variables inside the template. 

Thanks.

**Comment by jknack** [comment]
there is something but in your use case you will get ```items, name, color and reportDate```

Template has a collect method:

```
Template tmpl = ...
List<String> vars = tmpl.collect(TagType.VAR, TagType.SECTION);
```

in terms of callback you have two options:

1. collect all vars (previous API) and register them as helpers
2. use the MISSING_HELPER

```java
Handlebars hbs = new Handlebars().register("helperMissing", (ctx, options) -> {
   String name = options.helperName;
   //name will give you: items, name, color, reportDate
});
```

**Comment by khoubyari** [comment]
Thank you! We think the collect method will get us far enough for our current requirements.
