### ISSUE TITLE
@root doesn't work

### ISSUE THREAD

**Issue by reacher-lu** [jknack/handlebars.java#390]
For example，I have a json file

``` javascript

{
  name : xxx,
  item : [...]
}

```

when I use @root in handlbars.js like this

```javascript

{{#each item}}
    {{@root.name}}
{{/each}}

```

it's OK,but it does't work in handlebar.java,@root.name was undefined

**Comment by gvaish** [comment]
Isn't this a duplicate of #385, closed by https://github.com/jknack/handlebars.java/commit/a1923b6958c38d6f35333fa93ea1ba641302cc43 ?

**Comment by reacher-lu** [comment]
tks.
