### ISSUE TITLE
URLConnection may cause file handle leaks

### ISSUE THREAD

**Issue by plesiecki** [jknack/handlebars.java#393]
Hello!

Recently I that discovered method [URLTemplateSource.lastModified](https://github.com/jknack/handlebars.java/blob/0b1b12303cc74f3583433b3c15824164c74ced6f/handlebars/src/main/java/com/github/jknack/handlebars/io/URLTemplateSource.java#L115) may cause file handle leaks. It happens when you run your application from its pacakaged jar and handlebars reads last modification date from resource with URL like jar:file:/path/app.jar!/template.hbs.

**Comment by plesiecki** [comment]
I would like to propose a pull request for this issue.

**Comment by jknack** [comment]
I will look at the pull later, but don't think there is a leak. Everything is closed: https://github.com/jknack/handlebars.java/blob/master/handlebars/src/main/java/com/github/jknack/handlebars/io/URLTemplateSource.java#L125-131

**Comment by plesiecki** [comment]
I'm pretty sure there is ;) 

Some references:
http://www.genevski.com/2010/04/javaneturl-and-jarurlconnection-may.html
http://webcache.googleusercontent.com/search?q=cache:_sNS9oOvDnwJ:sourceforge.net/p/freemarker/bugs/189/+&cd=7&hl=pl&ct=clnk&gl=pl

Also https://github.com/kohsuke/file-leak-detector maybe useful for debugging.

**Comment by plesiecki** [comment]
Here goes steps to reproduce:
 
1. `git clone https://github.com/plesiecki/handlebars-spring-boot-starter-example.git && cd handlebars-spring-boot-starter-example`
2. Run `./gradlew installapp && build/install/handlebars-spring-boot-starter-example/bin/handlebars-spring-boot-starter-example`
3. In another console run `while true; do lsof -p $(jps | grep App | cut -d ' ' -f 1) | wc -l ; sleep 1; done` this is number of open files by app from step 2
4. `curl locahost:8080/` multiple times
5. Watch counter from step 3. It will increase by 35 each time you open localhost:8080/ - 35 it's a number of inclusion of handlebars template https://github.com/plesiecki/handlebars-spring-boot-starter-example/blob/master/src/main/resources/templates/hello.hbs#L8-L43.

**Comment by jknack** [comment]
odd, but thanks!

**Comment by jknack** [comment]
just realize a have the same bug in another (and awesome) project: https://github.com/jooby-project/jooby https://github.com/jooby-project/jooby/blob/master/jooby/src/main/java/org/jooby/internal/URLAsset.java :S

thanks again.

**Comment by plesiecki** [comment]
Glad I could help. Any idea when we can expect the next release?

BTW Jooby looks interesting ;)

**Comment by jknack** [comment]
will push a release now (will be available in 2/3 hours)

**Comment by plesiecki** [comment]
Cool! I've updated my https://github.com/allegro/handlebars-spring-boot-starter ;)
