### ISSUE TITLE
Application is wasting time on UrlTemplateSource.lastModified()

### ISSUE THREAD

**Issue by bgalek** [jknack/handlebars.java#396]
Hello! I have a problem when working with handlebars and a few templates (that won't ever change) on production environment. I have enabled guava cache on templates but still CPU wastes its time on waiting at UrlTemplateSource.lastModified() method. Why does it check lastModified? I assume that when my template files are inside jar package they won't ever change at runtime! Am I doing something wrong? 

My Handlebars config looks like:

HandlebarsViewResolver handlebarsViewResolver = new HandlebarsViewResolver();
handlebarsViewResolver.setFailOnMissingFile(false);
handlebarsViewResolver.setSuffix(DEFAULT_SUFFIX);
handlebarsViewResolver.setPrefix(DEFAULT_PREFIX);
handlebarsViewResolver.setCache(true);

**Comment by jknack** [comment]
what version? 2.2.3 got an enhancement on that: https://github.com/jknack/handlebars.java/issues/393

**Comment by bgalek** [comment]
ok, that's a point, I've moved to 2.2.3, it's better. But still - why do we have to call UrlTemplateSource.lastModified() when my template is cached and I'm running from jar? I don't expect any templates to change. What do You think about that?

**Comment by jknack** [comment]
No, we don't. I added that when I did it in order to allow cache+autoreload in prod env, this was a request from a user.

I will add a flag to Guava cache to skip that checks when the flag is on:

```
GuavaTemplateCache cache = ...
cache.setAutoReload(false);
```

cool?

**Comment by bgalek** [comment]
Cool! Looking forward to new release! Thx!
3 sie 2015 15:40 "Edgar Espina" <notifications@github.com> napisał(a):

**Comment by rzukow** [comment]
Are you sure it will help?

The key in all caches is TemplateSource, and in constructor of UrlTemplateSource we have:
  
public URLTemplateSource(final String filename, final URL resource) {
    this.filename = notEmpty(filename, "The filename is required.");
    this.resource = notNull(resource, "A resource is required.");
    this.lastModified = lastModified(resource);
  }

So fetching lastModified date will be performed for every single template usage.

**Comment by jknack** [comment]
it will, but as you already figure it out... requires a few more changes, like make the lastModified to build on request (lazy)

**Comment by rzukow** [comment]
The biggest problem I see now it's that lastModified is a part of hashCode ;)

**Comment by jknack** [comment]
I removed it! please try it and let me know.

Thanks!
