### ISSUE TITLE
Support for Handlebars 3.0.0

### ISSUE THREAD

**Issue by saamalik** [jknack/handlebars.java#400]
Hi,
Handlebars 3.0.3 is out. Will the latest version of Handlebars receive any love? =)

-Saad

**Comment by saamalik** [comment]
http://handlebarsjs.com/installation.html

**Comment by jknack** [comment]
it is already there:

```java
Handlebars hbs = new Handlebars();

hbs.handlebarsJsFile("/handlebars-v3.0.3.js");
```

Just download ```handlebars-v3.0.3.js``` and add it to the root of your classpath

**Comment by saamalik** [comment]
That's cool-- any plans to make 3.0.0 the new default for handlebars-maven-plugin? So we don't have to download and maintain our own copy?

**Comment by jknack** [comment]
yea, 3.0.0 will be the new default once handlebars.java 3.0.0 gets out!

but there is no release date yet... I'm busy working on http://jooby.org which I invited you to try and play :)

**Comment by denis111** [comment]
maybe straight to 4.x ? :)

**Comment by tgolden-andplus** [comment]
+1 for 4.x support. Your embedded ANTLr grammar doesn't appear to support the block syntax for partials which was added (the error message isn't fantastic either; I thought I was using the wrong handlebars.js file at first and didn't realize the error was actually coming from inside the Maven plugin itself).

**Comment by jknack** [comment]
Hi guys, can you collect what are the new feature of handlebars.js 4.x? For example, I don't know what is: block syntax for partials.

Thanks

**Comment by tgolden-andplus** [comment]
If you reference http://handlebarsjs.com/partials.html, one of the new features is the ability to supply fallback / additional content to a partial by invoking it in "block" form, like so:

> The normal behavior when attempting to render a partial that is not found is for the implementation to throw an error. If failover is desired instead, partials may be called using the block syntax.

    {{#> myPartial }}
      Failover content
    {{/myPartial}}

> Which will render Failover content if the myPartial partial is not registered.
> This block syntax may also be used to pass templates to the partial, which can be executed by the specially named partial, @partial-block. A template of

    {{#> layout }}
      My Content
    {{/layout}}

>with the layout partial containing

    Site Content
    {{> @partial-block }}

> Would render

    Site Content
    My Content

**Comment by tgolden-andplus** [comment]
It also seems like support for partial variables doesn't work either? I get different results compiling with handlebars from npm when using a construct like:

    {{> myPartial foo="bar"}}

If I'm interpreting https://github.com/wycats/handlebars.js/issues/410 correctly this was actually added back in the 2.x release line.

**Comment by jknack** [comment]
partial params does work! do you have problem with handlebar.js integration ?

**Comment by tgolden-andplus** [comment]
Hrm, perhaps my configuration of the Maven plugin is wrong then? I'm telling it to use the 3.0.3 handlebars.js file, but my outputted templates.js file does not include the proper hash params. I'll see if I can put together a self-contained test case.

**Comment by jknack** [comment]
handlebars.java 3.0.0 will comes with handlebars.js 3.0.0 as default
