### ISSUE TITLE
Only the first line of a partial is indented

### ISSUE THREAD

**Issue by vivin** [jknack/handlebars.java#401]
I am not sure if I'm doing something wrong or if I have things configured wrong. I'm only seeing the first line of a partial indented, and not subsequent lines. I am a mustache/handlebars noob so it might be possible that I am doing something wrong!

I have the following in my `src/main/resources`:

```
./src/main/resources/
└── handlebar
    └── templates
        ├── child.hbs
        └── parent.hbs
```

The contents of the files are as follows:

**parent.hbs**
```
parent line 1
    {{> child}}
parent line 2
```

**child.hbs**
```
child line 1
child line 2
```

When the template is applied, I see:

```
parent line 1
    child line 1
child line 2
parent line 2
```

The code in Java that loads and applies the templates is as follows:

```java
TemplateLoader loader = new ClassPathTemplateLoader();
loader.setPrefix("/handlebar/templates");
loader.setSuffix(".hbs");

Handlebars handlebars = new Handlebars(loader);
System.out.println(template.apply(null));
```

The version I am using is 2.2.3 (the latest one in Maven central). I tried this with 2.2.2 and got the same behavior. Thanks!

**Comment by jknack** [comment]
Nothing wrong with your code, but you need to enabled it:

```java
...
Handlebars handlebars = new Handlebars(loader)
    .prettyPrint(true);
```

Keep in mind it will take a few ms more to do it, so use it if you think is strictly necessary.

Also, invite you to try my micro web framework: [jooby](http://jooby.org)!

**Comment by vivin** [comment]
Ah, ok! But wouldn't that mess up things that use whitespace control? Or does using prettyPrint take care of that?

**Comment by jknack** [comment]
prettyPrint follows Mustache Spec/Rules around whitespaces and newlines. In theory, you shouldn't have any issue/problem.

**Comment by vivin** [comment]
Awesome! Thank you!

**Comment by vivin** [comment]
Btw, jooby looks pretty nice!

**Comment by vivin** [comment]
One more question. Would using a partial inside a helper cause it to be unindented? I made my own helped to look stuff up from a map using a dynamic key. The template looks like this:

```

{{#withKey ../myMap key=this}}
    {{#if this.length}}
        {{#each this}}
            {{> child}}
        {{/each}}
    {{/if}}
{{/withKey}}
```

I'm noticing that there's no indentation here.

**Comment by vivin** [comment]
It does work in the normal case though.

**Comment by jknack** [comment]
can you add an example of expected output?

tks

**Comment by vivin** [comment]
Sure thing!

Here is my helper code:

**helpers.js**:
```javascript
Handlebars.registerHelper('withKey', function(map, options) {
    return options.fn(map[options.hash.key] || []);
});
```

I'm building up the model and applying the template as follows (a contrived example similar to my use-case):

```java
List<String> items = new ArrayList<>();
items.add("a");
items.add("b");
items.add("c");

Map<String, List<String>> map = new HashMap<>();
List<String> list = new ArrayList<>();
list.add("one");
list.add("two");
list.add("three");

map.put("a", list);

list = new ArrayList<>();
list.add("four");
list.add("five");
list.add("six");

map.put("b", list);

list = new ArrayList<>();
list.add("seven");
list.add("eight");
list.add("nine");

map.put("c", list);

Map model = new HashMap();
model.put("items", items);
model.put("map", map);

TemplateLoader loader = new ClassPathTemplateLoader();
loader.setPrefix("/handlebar/templates");
loader.setSuffix(".hbs");

handlebars = new Handlebars(loader).prettyPrint(true);
try {
    handlebars.registerHelpers("handlebar/helpers.js", this.getClass().getClassLoader().getResourceAsStream("handlebar/helpers.js"));
} catch(Exception e) {
    throw new HandlebarsException("Error while registering helpers: " + e.getMessage(), e);
}

Template template = handlebars.compile("parent");
Context context = Context.newBuilder(model).build();
System.out.println(template.apply(context));
```

The templates look like this:

**parent.hbs**:
```hbs
{{#each items}}
parent line 1 {{this}}
    {{#withKey ../map key=this}}
        {{#each this}}
    {{> child}}
        {{/each}}
    {{/withKey}}
parent line 2 {{this}}
{{/each}}
```

**child.hbs**:
```hbs
child {{this}}

```

The output I get is:

```
parent line 1 a
child one
child two
child three
parent line 2 a
parent line 1 b
child four
child five
child six
parent line 2 b
parent line 1 c
child seven
child eight
child nine
parent line 2 c
```

But what I would expect is:

```
parent line 1 a
    child one
    child two
    child three
parent line 2 a
parent line 1 b
    child four
    child five
    child six
parent line 2 b
parent line 1 c
    child seven
    child eight
    child nine
parent line 2 c
```

It's entirely possible I'm making some sort of fundamental mistake. As I mentioned earlier, I'm a handlebars/mustache noob!

**Comment by vivin** [comment]
@jknack Were you able to verify this behavior on your end?
