### ISSUE TITLE
Repeated previous partial parameter values

### ISSUE THREAD

**Issue by karlhorky** [jknack/handlebars.java#402]
We are experiencing an unexpected behavior with the partial parameters implemented for #350. It appears to be reusing the previous value of the parameter passed to the partial.

*index.hbs*
```hbs
{{> user name="Bob" age="31"}}
{{> user age="29"}}
```

*user.hbs*
```hbs
<div><b>{{name}}</b> {{age}}</div>
```

*expected output*
```html
<div><b>Bob</b> 31</div>
<div><b></b> 29</div>
```

*real output*
```html
<div><b>Bob</b> 31</div>
<div><b>Bob</b> 29</div>
```

We are using Handlebars.java v2.2.0.

**Comment by antoniocapelo** [comment]
Yes, I've just stumbled with that problem

**Comment by karlhorky** [comment]
Thanks @jknack !

**Comment by jknack** [comment]
you're welcome, next release will be available tomorrow.

also, I invite you to try: http://jooby.org :)
