### ISSUE TITLE
No way (or example ) to access JSON objects from template

### ISSUE THREAD

**Issue by Omasiri** [jknack/handlebars.java#405]
There is no way (or example) to handle the rendering of JSON objects in the template. 

For example: Given an array of json objects like{people: [{'name':'John', 'age':'12'},{'name':'Jane', 'age':'4'}]}, accessing properties of the array from the template does not work.
<ul>
{{#each person}}
   <li> {{this.name}} </li>
{{/each}}
</ul>

Is there a way to handle this? 

Node: I am currently using vertx with HandlebarsTemplateEngine

Thanks

**Comment by jknack** [comment]
what do you mean by JSON? how do you parse/serialize from/to JSON?

JSON isn't a native format in Java. The way to deal with custom formats is via a handlebars value resolver: http://jknack.github.io/handlebars.java/stack.html

Also, if you use Jackson for JSON, there is a JsonNode value resolver here: https://github.com/jknack/handlebars.java/blob/master/handlebars-jackson2/src/main/java/com/github/jknack/handlebars/JsonNodeValueResolver.java
