### ISSUE TITLE
How java object serialization works with handlebars?

### ISSUE THREAD

**Issue by nykolaslima** [jknack/handlebars.java#408]
Hello guys,

We have a Handlebars template that has a code like this:
```
{{#car}}
 Car Price: {{carPrice}}
{{/car}}
```

In our java object we have some getters:
```
public boolean isCar() {
 return isCar;
}

public Double getCarPrice() {
 return carPrice + 10.0;
}
```

The problem is, when `isCar` is false, the `Double` `carPrice` field is null. So if we call `getCarPrice` method, we got an NullPointerException.

When the handlebars template is rendered, the `getCarPrice` method is being called, but the `isCar` method is returning `false`.

My doubt is, the `handlebars.java` calls all getters in order to create a javascript representation of the java class or it calls the getters on demand, while it's rendering the template?

**Comment by jknack** [comment]
on demand, ```getCarPrice``` won't call it if isCar returns ```false```
