### ISSUE TITLE
@key for an object does not work

### ISSUE THREAD

**Issue by annapon** [jknack/handlebars.java#412]
I have a JSON such as the following:
{
"managers":[
    {"firstName":"John", "lastName":"Doe"},
    {"firstName":"Anna", "lastName":"Smith"},
]
"staff":[
    {"firstName":"John", "lastName":"Smith"},
    {"firstName":"Peter", "lastName":"Jones"}
]
}

I am trying to get the value of the keys (managers, staff) here under the main object. My keys are dynamically generated (although that should not make a difference?), and using @key in my template (such as {{@key}}:) does not seem to give me any value.

**Comment by jknack** [comment]
There is no native support for JSON in Java. Are you using Maps? Beans? What is your object type?

**Comment by mikert** [comment]
I'm on the latest release and ran into this issue as well. I'm using Jackson. This is the code that fails with @key:

```Groovy
private Context getContextForJson(String json) {
        JsonNode jsonNode = new ObjectMapper().readValue(json, JsonNode.class)
        Context
            .newBuilder(jsonNode)
            .resolver(JsonNodeValueResolver.INSTANCE,
            JavaBeanValueResolver.INSTANCE,
            FieldValueResolver.INSTANCE,
            MapValueResolver.INSTANCE,
            MethodValueResolver.INSTANCE
        )
        .build()
    }```

**Comment by mikert** [comment]
For what it's worth, I found that just using a Map would work just fine. There are ways with jsonlib to get a Map from the JSON. We use Groovy, so the JsonSlurper works for this. Ex:

```Groovy

Context
            .newBuilder(new groovy.json.JsonSlurper().parseText(json))
            .resolver(JsonNodeValueResolver.INSTANCE,
            JavaBeanValueResolver.INSTANCE,
            FieldValueResolver.INSTANCE,
            MapValueResolver.INSTANCE,
            MethodValueResolver.INSTANCE
        )
        .build()
```

**Comment by nobuoonodera** [comment]
Hi
ObjectNode is always converting to map. Then, ObjectNode could not set to template. Is this proper behavior?

**Template**
`
{
  "node1": {{object}}
}
`
**Insert data**
`
{
  "object":{
    "nest1":"value1",
    "nest1":"value2"
  }
}
`

The result is follwoing.
`
{
  "node1":{
    nest1="value1",
    nest1="value2"
  }
}
`
