### ISSUE TITLE
Java 8 optionals in context

### ISSUE THREAD

**Issue by mohamnag** [jknack/handlebars.java#413]
How is somebody supposed to use Java 8 Optionals in context objects? lets say my context is POJO who has two fields:
```java
class SamplePojo {
    String field1 = "field1";
    String field2 = "field2";

    public String getField1() {
        return field1;
    }

    public Optional<String> getField1() {
        return Optionals.ofNullable(field2);
    }
}
```

when I use them both in template, after context being applied I get following:

```html
<p>value of "field1"</p>
<p>value of "Optionals[field2]"</p>
```

Is there a way for handlebars.java to get the value instead of converting the whole optionals to string?

**Comment by jknack** [comment]
you need a custom value resolver, there is some doc here: http://jknack.github.io/handlebars.java/stack.html

**Comment by mohamnag** [comment]
thanks, I didn't know about resolvers and just enabling following two resolvers solved the problem:
```java
FieldValueResolver.INSTANCE,
JavaBeanValueResolver.INSTANCE
```

**Comment by jknack** [comment]
cool!

Also, invite you to try http://jooby.org a Micro web framework
