### ISSUE TITLE
Lookup helper is not working the same way as it works in Handlebars.js

### ISSUE THREAD

**Issue by breneser** [jknack/handlebars.java#418]
I think the way lookup helper is implemented is not exactly compatible with Handlebars.js lookup helper.

With Handlebars.js I am able to lookup arrays with indices or objects with property names(keys) , but with Handlebars.java I can not lookup if the object I am looking up is not a parent or ancestor of the current context.

Please check the JSFiddle example in the link below.

http://jsfiddle.net/pef2f8rb/1/

My data is as follows:

```
{
	series: [
		"Test A",
		"Test B",
		"Test C"
	],
	types: {
			"Test A": "bar",
			"Test B": "bar",
			"Test C": "line"
	}
}
```

Now, the following code is fine with Handlebars.js and renders "bar bar line", but it does not render anything in Handlebars.java

```
{{#each series}} {{lookup ../types this}}{{/each}}
```

In order to get this work I had to use with helper as follows

```
{{#each series}}{{#with ../types}}{{lookup this ..}}{{/with}}{{/each}}
```

Looking at the source code for Lookup helper I noticed it says the helper is useless. I think this subtle difference makes it useful, it is a general purpose helper rather than a context lookup helper. It is not very clear in Handlebars documentation though.

**Comment by jknack** [comment]
thanks! will have a look later :)

Also, I invite you to try http://jooby.org

**Comment by breneser** [comment]
Looks interesting, will look into it :+1:
