### ISSUE TITLE
Include MapTemplateLoader in the public API

### ISSUE THREAD

**Issue by mhfrantz** [jknack/handlebars.java#419]
This class is used in testing in-memory partials, which is exactly how I want to use it.

**Comment by jknack** [comment]
do you need it for tests too?

if so, try the test jar:

```xml
  <dependency>
      <groupId>com.github.jknack</groupId>
      <artifactId>handlebars</artifactId>
      <version>2.3.0</version>
      <scope>test</scope>
      <classifier>tests</classifier>
    </dependency>
```

MapTemplateLoader should be there, but also all the support code for testing handlebars

**Comment by mhfrantz** [comment]
OK, the classifier works for me.  Thanks!
