### ISSUE TITLE
Partials do not seem to be using path from a Custom View Resolver 

### ISSUE THREAD

**Issue by ncmadhan** [jknack/handlebars.java#420]
I have a Spring MVC application for which I'm using handlebars in the view layer. 

I have multiple template folders within a single "themes" folder and the views are required to be resolved from a particular template folder based on a particular parameter present in the user's session. 

```
/themes
        ---- /theme-1
                 --- index.html
                 --- body.html
        ---- /theme-2
                 --- index.html
                 --- body.html
```

For doing this, I created a CustomHandlebarsViewResolver. This is configured in MvcConfig.java with prefix as the parent "themes" folder. I then override the buildView() method to modify the viewName dynamically by appending the {folder-name} to the viewName.

CustomHandlebarsViewResolver.java
```
public class ThemeBasedViewResolver extends HandlebarsViewResolver {
	
	@Override
	protected AbstractUrlBasedView buildView(String viewName) throws Exception {
              // Get folderName from session
              viewName = folderName + viewName;   
              return super.buildView(viewName);
        }
```

MvcConfig.java

```
@Bean
	public ThemeBasedViewResolver handlebarsViewResolver() {
		ThemeBasedViewResolver bean = new ThemeBasedViewResolver();
		bean.setPrefix("/themes/");
		bean.setSuffix(".html");
		bean.setOrder(1);
		return bean;
	}
```

Now, if I return "index" in my controller, this gets resolved as /themes/{folder-name}/index.html by the Custom ViewResolver. This is fine. 

However within index.html I have included a partial like {{> body}}. body.html is present in the same folder as index.html.

index.html

```
<html>
<body>
{{>body}}
....
<body>
<html>
```

As per my current understanding, partial names are resolved in the same way as views by handlebars.java's spring module.

So {{>body}} should have resolved to /themes/{folder-name}/body.html. However, it resolves to /themes/body.html. The code doesn't seem to reach the buildView() method of CustomViewResolver. What am I doing wrong here?

**Comment by jknack** [comment]
nothing wrong, but you won't be able to do it bc partial resolution isn't done contextually. Partials are always resolved from  "root" or "prefix" option.

another possible solution will be to apply dynamic partials:

```
{{> (partialWithTheme "body") }}
```

Here: ```partialWithTheme``` is a helper that check your session theme and resolve the "body" template by prefixing the "theme"
