### ISSUE TITLE
v4: Inline Partials

### ISSUE THREAD

**Issue by karlhorky** [jknack/handlebars.java#433]
wycats/handlebars.js#1018

**Comment by jknack** [comment]
inline partials will be available in the next release... but don't think decorators will be. do you find them useful? I'm struggling to see the diff between decorators and helpers

**Comment by karlhorky** [comment]
Hm, looks like they are used for annotating particular blocks with metadata as well as to wrapping them in behaviors. For instance, [here](https://github.com/wycats/handlebars.js/issues/404#issuecomment-11914641) an early concept of decorators shows how they could be used to build up a table without repetition for the html elements.

Would be useful, but I can understand if this would mean a lot of work.

Should I maybe separate the decorators part out into another pull request?

**Comment by jknack** [comment]
isn't just the amount the work.. so far all the examples I saw mutate/changes the state of the template ```options.fn``` or similar... that is a bad practice but also hard to implement in static typed languages like Java.

So, yes. Please open a new issue for decorators now.

Thanks

**Comment by karlhorky** [comment]
Sounds good, opened one at #442.

**Comment by jknack** [comment]
done: https://github.com/jknack/handlebars.java/commit/b046834a12943215b56b081ac13c7701bd5a3dfa

**Comment by karlhorky** [comment]
Wow, so much new stuff! Thanks!

**Comment by jknack** [comment]
:)
