### ISSUE TITLE
v4: raw block helpers

### ISSUE THREAD

**Issue by jknack** [jknack/handlebars.java#444]
```
{{{{raw-helper}}}}
  {{bar}}
{{{{/raw-helper}}}}
```

see https://github.com/wycats/handlebars.js/pull/730

and http://handlebarsjs.com/block_helpers.html#raw-blocks

**Comment by devnewton** [comment]
Hello,

I don't get how to write a working raw helper.

`public class RawHelper implements Helper<Object> {

    @Override
    public CharSequence apply(Object t, Options options) throws IOException {
        return options.fn.text();
    }

}`

`{{{{raw}}}}
{{myhelperforclientside test}}
{{{{/raw}}}}`

This give me a:

com.github.jknack.handlebars.HandlebarsException: could not find helper: 'myhelperforclientside'
