### ISSUE TITLE
Fix for issue #430 breaks url encoding

### ISSUE THREAD

**Issue by dontgitit** [jknack/handlebars.java#445]
Hi, 

The fix for #430 breaks urls with = in them. For example, consider the context
```
{ "url": "http://google.com/foo?bar=baz" }
```
The template ```{{url}}``` used to render to "http://google.com/foo?bar=baz", but now it renders as "http://google.com/foo?bar&#x3Dbaz" which completely breaks URL encoding in existing templates.

Are there any workarounds for this other than using triple braces to not escape? Should we be using some helper that specifically knows how to render a url? Is there any way to upgrade without breaking existing templates?

Thanks for your help! Specifically looking forward to using the named block parameters!

**Comment by jknack** [comment]
yikes! hmm handlebars.js has the same problem.. wonder what they do? @karlhorky any comment here?

**Comment by jknack** [comment]
hmm I try it here: http://tryhandlebarsjs.com/ but seems chrome known how to deal with &#x3D

**Comment by dontgitit** [comment]
It doesn't seem to work from email clients (which is our use case)

**Comment by jknack** [comment]
yea, email clients are very tricky... so a probably easy work-around will be to provide your own escaping-strategy... which basically ignores ```=```

```java
Handlebars hbs = new Handlebars().with(new MyEscapeStrategy());
```

Next release will provide an escape strategy, that will ignore ```=```, but for now you can use your own and update later to ```4.0.1``` 

Cool?

**Comment by dontgitit** [comment]
I like it! Thanks for the suggestion!

**Comment by jknack** [comment]
Excellent! Also, I invited you to try http://jooby.org/ a micro and super fast web framework!

**Comment by jkwatson** [comment]
This appears to still be broken in 4.0.2.  Any update to when it will be fixed?

**Comment by jknack** [comment]
No idea if this is sendgrid bug or not.. but I forgot about adding new escaping strategy that ignores ```=```.

So, yes, you have to create your own :S

Can you raise a new issue about getting back the old strategy?

Thanks

**Comment by jkwatson** [comment]
https://github.com/jknack/handlebars.java/issues/465

Thanks!

**Comment by techyrajeev** [comment]
I am using 4.0.5 but I am still facing the issue. Has it been fixed yet?

**Comment by knoxxs** [comment]
You can pass it a custom strategy

```java
handlebars = new Handlebars().with(new EscapingStrategy.Hbs(new String[][]{
                {"<", "&lt;" },
                {">", "&gt;" },
                {"\"", "&quot;" },
                {"'", "&#x27;" },
                {"`", "&#x60;" }
        }));
```

This is HBS3 without `&`
