### ISSUE TITLE
Question about JavaScript files

### ISSUE THREAD

**Issue by tmarrs** [jknack/handlebars.java#446]
I'm new to Handlebars Java, and I've got a question about the JS files.
It looks like Handlebars Java is a pure Java implementation of Handlebars, so I don't see any dependency there (i.e., there's no call to Nashorn - e.g., javax.script). 

So, how are the Handlebars JS files used in this repository?

**Comment by jknack** [comment]
welcome to handlebars.java!

Indeed it is a pure Java implementation!! The way you can integrate or use handlebars.js is via:

1. you have a template that is rendered in the server, but then also in the client. examples of these are list/table results, where for example you render the first page in the server and then new searches, paging, etc.. is handle in the client via ajax calls and handlebars.js

2. you have some handlebars templates and you want to compile them into JavaScript at build time. This can be achieved via a [maven plugin](https://github.com/jknack/handlebars.java/tree/master/handlebars-maven-plugin). When build time is not an option there is a ```precompile``` helper: https://github.com/jknack/handlebars.java#precompile

3. you wrote a few helpers in JavaScript and you want to use them at client but also server side. Here, handlebars.java use Rhino (not nashorn yet) to run the helpers in Java. Here is a simple example on how to do it: https://github.com/jknack/handlebars.java#with-plain-javascript

This link might be helpful too: http://jknack.github.io/handlebars.java/meeting.html

Let me know if you have questions.

**Comment by tmarrs** [comment]
Thanks for the welcoming words. I'm so glad it's a pure Java implementation. This is important because I'll need to use Handlebars Java in an Android application.

**Comment by jknack** [comment]
Nice! Also, if you like handlebars.java I invited you to try: http://jooby.org

**Comment by tmarrs** [comment]
Thanks for clarifying everything. I'll take a look at jooby.
I'll let you know how the Android project works out.
