### ISSUE TITLE
HandlebarsException: Could not find helper: 'log' 

### ISSUE THREAD

**Issue by tlovett-rmn** [jknack/handlebars.java#447]
The README states that 'log' is one of the built-in helper, but I'm getting this error:
```
com.github.jknack.handlebars.HandlebarsException:
java.lang.IllegalArgumentException:
could not find helper: 'log'
```

For line:
```hbs
{{#log "hello"}}{{/log}}
```

Do I need to manually register it? I couldn't find it in the codebase.

**Comment by jknack** [comment]
You're right! will add one
