### ISSUE TITLE
Different context behaviour in block helper for  js and java hbs 

### ISSUE THREAD

**Issue by husayt** [jknack/handlebars.java#448]
Basically, i have different behaviour user defined helper's context in Java and Js versions. To demonstrate here is the example. I define my `is` block helper and expect it's context to behave the same as `if` context, both in Java and JS.
But for `is` in Java version to work i have to add `../` to `this`. That is wrong. `{{this}}` should work for all 4 cases..

data.json
```
{letters:['a','b','c','d']}
```

my.hbs -for js
```
{{#each letter}}
{{#if this}}{{@index}}={{this}}{{/if}}
{{#is 0 0}}{{@index}}={{this}}{{/is}}
{{/each}}
```
my.hbs - for java
```
{{#each letter}}
{{#if this}}{{@index}}={{this}}{{/if}}
{{#is 0 0}}{{@index}}={{../this}}{{/is}}
{{/each}}
```
helpers.js
```
Handlebars.registerHelper('is', function(value, test, options) {
                if (value === test) {
                    return options.fn(this);
                } else {
                    return options.inverse(this);
                }});
```

**Comment by jknack** [comment]
odd, will look later, but there is a workaround for4.x

```
{{#each letter as | c |}}
{{#if this}}{{@index}}={{c}}{{/if}}
{{#is 0 0}}{{@index}}={{c}}{{/is}}
{{/each}}
```

**Comment by husayt** [comment]
Thanks Edgar. But there is something else. I have been investigating number of issues related to js helpers in HBS java and I am sure we have a number issues there. 

I am still trying to understand better.
But here is one more example, this time i am using `each- as |c|` like you advised and the same helpers.

let's first run this in [hbs.js -http://tryhandlebarsjs.com/](http://tryhandlebarsjs.com/)

template
```
{{#each this as |c|}} {{c}} - {{#is 0 (remainder c 2)}}even{{else}} odd{{/is}} 
{{/each}}
```

context  `[4,5,6,7,8]`

helpers 
```
Handlebars.registerHelper('is', function(value, test, options) {
                if (value == test) {
                    return options.fn(this);
                } else {
                    return options.inverse(this);
                }});


Handlebars.registerHelper('remainder', function (value, divisor) {
                return value % divisor;
            });
```

you get as expected:
```
 4 - even 
 5 -  odd 
 6 - even 
 7 -  odd 
 8 - even 
```

running the same in Java i get `Missing helper: (remainder c 2)` warnings
and  tehn
```
 4 - even 
 5 - even
 6 - even 
 7 - even 
 8 - even 
```

So something to do with one helper working inside another helper.

Note,
`{{remainder odd 2}}` works on it's own

it even works from inside `is ` e.g. `{{#is 0 (remainder odd 2)}}`

but it doesn't work when `is` inside `each` i.e.  `{{#each this as |c|}}  - {{#is 0 (remainder c 2)}}`

**Comment by jknack** [comment]
fixed are in master now... everything should work except for a minor detail, ```is``` helper must be like this:

```js
Handlebars.registerHelper('is', function(value, test, options) {
                if (value == test) {
                    return options.fn(this);
                } else {
                    return options.inverse(this);
                }});
```

In short, you can't use ```===``` while comparing numbers in rhino :S, numbers are converted to ```java.lang.Double```.

@husayt thanks!

**Comment by husayt** [comment]
Thanks  @jknack. It works. Looking forward for new 4.0.1 release.

**Comment by jknack** [comment]
```4.0.1``` is out
