### ISSUE TITLE
Suppress "Helper been replaced by " warnings

### ISSUE THREAD

**Issue by husayt** [jknack/handlebars.java#450]
Hi, i have to override a number of JS helpers with Java alternatives (due to some incompatibilities) and that means I get  a lot of ` Helper 'xxx' has been replaced by 'xxx' ` warning in our logs. This makes it very difficult to spot real issues for us. 

Is there any way to suppress this? Even better it would be able to suppress this on selected set of helpers, so we could see warning when unexpected overrides take place.

**Comment by jknack** [comment]
You can turn off/set-log-level via slf4j/logback. But also, you should see those logs once (at application startup) right?

Don't see a huge problem, it confirm your changes were applied.

**Comment by husayt** [comment]
Edgar, thanks for prompt reply. 

The problem with doing it via slf4j, it will hide all logs from HBS. I would rather just hide the selected ones or at least to have them as info. 

They wouldn't be a problem if only that would happen in the beginning. For us it happens each time we run templates, that means all the time. (we have to load selected partials, for each generation and for that reason, we can reuse the same hbs instance )

**Comment by jknack** [comment]
so, you have multiple-instances of Handlebars, right?

maybe a custom logger will do it, so you can turn it off and leave the normal hbs logger untouch.
