### ISSUE TITLE
Rhino optimization option

### ISSUE THREAD

**Issue by nanamikon** [jknack/handlebars.java#453]
According to https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino/Optimization ,   different optimization level affect 
js execution 。
 
In my situation,  performance is much more import and helper  is simple,  so higher optimization level will be better 。   May I send a pull request  for  adding an option to setting optimization level ?

@see com.github.jknack.handlebars.internal.js.RhinoHandlebars
```java
    /**
     * Creates a new Rhino Context.
     *
     * @return A Rhino Context.
     */
    private Context newContext() {
      Context ctx = Context.enter();
      ctx.setOptimizationLevel(-1);
      ctx.setErrorReporter(new ToolErrorReporter(false));
      ctx.setLanguageVersion(Context.VERSION_1_8);
      return ctx;
    }
```

**Comment by jknack** [comment]
sure, np. how do you feel we can expose the optimization level?

**Comment by nanamikon** [comment]
Sorry for late reply ， i submit a pull request here  https://github.com/jknack/handlebars.java/pull/454

**Comment by nanamikon** [comment]
Sorry for late reply, I have submitted a pull request here https://github.com/jknack/handlebars.java/pull/454
