### ISSUE TITLE
FastStringWriter - add initial size for StrBuilder

### ISSUE THREAD

**Issue by mhankus** [jknack/handlebars.java#456]
FastStringWriter class uses StrBuilder from commons lang. StrBuilder is constructed with default initial capacity which is 32 bytes, which is then expanded. Rule describing problem is created in PMD - but it is about StringBuffer, but problem is the same - https://pmd.github.io/pmd-5.4.1/pmd-java/rules/java/strings.html#InsufficientStringBufferDeclaration
I performed some testing, and most allocations during runtime comes from StrBuilder.ensureCapacity (called from FastStingWriter.append which calls StrBuilder.append)

Please initialize StrBuilder with bigger initial capacity (for example with template size, or other fixed number bigger than 32 bytes)

**Comment by jknack** [comment]
Buffer is 16k now.
