### ISSUE TITLE
Raw blocks don't work in hbs Java

### ISSUE THREAD

**Issue by husayt** [jknack/handlebars.java#468]
```
{{{{raw-helper}}}}
  {{bar}}
{{{{/raw-helper}}}}
```

This doesn't work in handlebars java. But is specified [here] for hbs js (http://handlebarsjs.com/block_helpers.html#raw-blocks)

**Comment by jknack** [comment]
did you define the ```raw-helper```?

You must to define your helper if you try it here: http://tryhandlebarsjs.com. It output nothing, unless of course you register the ```raw-helper```

Here is handlebars.java output with and without the ```raw-helper```

```java
public class Issue468 extends v4Test {

  @Test
  public void rawHelperShouldWork() throws IOException {
    shouldCompileTo("{{{{raw-helper}}}}{{bar}}{{{{/raw-helper}}}}",$, "");

    shouldCompileTo("{{{{raw-helper}}}}{{bar}}{{{{/raw-helper}}}}",$("helpers", $("raw-helper", new Helper<Object>() {
      @Override
      public CharSequence apply(final Object context, final Options options) throws IOException {
        return options.fn();
      }
    })), "{{bar}}");
  }

}
```

It works as expected

**Comment by husayt** [comment]
Hi Edgar, 
thanks for your reply . Sorry I forgot to mention,  that `raw-helper` is defined  like this
```
Handlebars.registerHelper('raw', function(options) {
  return options.fn();
});
```
So maybe the issue, is that I define it in JS. Here is the error I get:

>Can't find method com.github.jknack.handlebars.internal.js.RhinoHandlebars$OptionsJs.fn().

**Comment by jknack** [comment]
oh good, yea the problem is in javascript

**Comment by husayt** [comment]
I got a few JS helpers which use `options.fn()`, this means none would work in HBS java. Is it something which can be fixed, or should i better rewrite them all in java?
