### ISSUE TITLE
HighConcurrencyTemplateCache does not detect changes in file

### ISSUE THREAD

**Issue by breneser** [jknack/handlebars.java#474]
I have been using Handlebars java version 2.2.1 for a long time now using HighConcurrencyTemplateCache when developing. It always detected changes I made, until I updated version to 4.0.3 ( I remember trying version 3 before, can't see version 3 now though, had the same problem with it )

I can see the changes after restarting the app.

This is how I initialize Handlebars

`new Handlebars(new FileTemplateLoader(templatesDirectory, templatesSuffix)).with(new HighConcurrencyTemplateCache())`

**Comment by DornieDortsch** [comment]
There is a new flag `TemplateCache.setReload(boolean reload)`. Check this out.

**Comment by breneser** [comment]
Just tried setting reload flag. Still not reloading...

**Comment by breneser** [comment]
Actually that worked, sorry could not see the change as response was not modified, it works now.
