### ISSUE TITLE
length misbehavior

### ISSUE THREAD

**Issue by husayt** [jknack/handlebars.java#476]
Hi,
here is another Js helper inconsistency. I got a helper which is defined like this 
```
 length: function (array) {
                return (!array) ? 0 : array.length;
            },
```

It works as expected in js, but in java it has two problems.

```
        List<String> data = Lists.newArrayList("1","3","4");
        String[] arr= {"1","3","4"};

        String str1 = hbs.compileInline("{{length this}}").apply(arr);
        String str2 = hbs.compileInline("{{length this}}").apply(data);
```
First one returns `undefined` and second one `3.0`.
I would expect `3` result from both.

**Comment by jknack** [comment]
fixed the ```undefined``` error... now both will give you: ```3.0```. 

Rhino does that and as far I can see there is no way to get just ```3```

A workaround for js/rhino is to use ```.toFixed()```

```js
return array.length.toFixed();
```

**Comment by husayt** [comment]
The problem with `.toFixed()` is that it returns String and that can make a big difference if `length` helper is used inside of another helper.

**Comment by jknack** [comment]
oh I missed that! but still we can't do anything here this is how rhino works :S
