### ISSUE TITLE
Flushing Html after head tag

### ISSUE THREAD

**Issue by marcelgulbahar** [jknack/handlebars.java#481]
Implementing the ability to flush in some points would really give a nice performance boost to the html generation of websites.

More info: http://www.websiteoptimization.com/speed/tweak/flush/
Freemarker Reference: http://freemarker.incubator.apache.org/docs/ref_directive_flush.html

**Comment by jknack** [comment]
thanks! looks cool! but will have to do a closer look before given you a real answer.

also, it depends on the web server you pick and how flexible it is for handling chunks. For example, a good number of Java server uses 16k chunk sizes and they won't flush until you reach that limit...follow me? it depends heavily on the web server.

talking about Java web servers... I invited you to try: http://jooby.org :)
