### ISSUE TITLE
Boolean sub expression within if tags always resolve to true

### ISSUE THREAD

**Issue by chli1** [jknack/handlebars.java#483]
I'm tryping to write a boolean Sub expression in javascript to be used within {{#if}} tags, but they do not work as expected.

Assuming the following javascript helper:

```
Handlebars.registerHelper('equal', function (arg1, arg2) {
    return (arg1 == arg2);
});
```
Now I try to use the helper within my template:

```
{{#if (equal arg "foo")}}
foo
{{/if}}
```
But the if-expression is always resolved as true, because the return value from sub expression is converted to String ("false") and "false" is not falsy when evaluated by the built-in IfHelper (options.isFalsy(context)).

However, I'm not sure how to fix this easily because also in JS the string "false" is evaluated to true, so the behaviour of the Options.isFalsy() method is correct. The problem is the conversion to String before. One solution would be, that the Helpers should be able to return any value, not just CharSequence objects but that would change large amounts of the domain model.

My current work-around is to return `true` if `arg1 == arg2` and `null` if not, because `null` will be evaluated as falsy value.

**Comment by jknack** [comment]
did you try: ```return (arg1 === arg2);```?

**Comment by chli1** [comment]
@jknack yes, I did, but no difference. I've implemented some more comparison operators but none of them work without the work-around.

**Comment by jknack** [comment]
yea, I answered too early... now I got what you mean and you're right. Does this work in handlebarjs?

**Comment by chli1** [comment]
Yes, in pure handlebars.js the expression works, I've created a minimal example in [jsfiddle](https://jsfiddle.net/qox889g8/).

**Comment by jknack** [comment]
keep the workaround for now... but also created #484 just for you ;)

Also, invite you to try: http://jooby.org

**Comment by BTermorshuizen** [comment]
The if helper renders based on 'options.isFalsy(context)'. This method returns true when an empty value is returned, false otherwise. Wouldn't a simple change in the method Options.isFalsy(final Object value) to return true also when the value parameter is a char sequence that equals to 'false'. 
This would allow the construction of helpers like 'and', 'or', 'not' and 'equal' and combining them in an 'if' like:
{{#if (and true (or true false))}}true result{{else}}false result{{/if}}
