### ISSUE TITLE
nested lookup helper in with

### ISSUE THREAD

**Issue by jhaggerty** [jknack/handlebars.java#489]
I'm attempting to use a lookup nested in a with (see https://jsfiddle.net/haggerty/jm6estrt/ for a JavaScript example). in handlebars.java, I'm seeing LookupHelper find the correct object, but since it's returning a CharSequence, the WithHelper is treating the context as a string. If I directly reference the object in the with, it works fine.

**Comment by dontgitit** [comment]
I'm not sure the fiddle can be made to work with this version; if `lookup` is implemented as a helper, I think its `apply` method must return a `CharSequence`, so there's no way to return an `Object` back to the `with` block. However, it's possible to just rewrite `lookup` itself a block helper. That's the solution I'm taking in my project. It looks like this (Scala):

```
  def apply(context: Object, options: Options) = {
    val ctx = Context.newBuilder(options.context, context).build
    val res = ctx.get(options.param(0).toString)
    val newCtx = Context.newBuilder(options.context, res).build
    options.apply(options.fn, newCtx, java.util.Arrays.asList(res))
  }
```

usage, given your books sample:
```
<h1>Books in My Library</h1>
    <ul>
        {{#each myLibrary}}
        <li>{{#lookup @root.booksByIsbn . as |book|}} {{book.title}} by {{book.author}} ({{book.isbn}}) {{/lookup}}</li> 
        {{/each}}
    </ul>
```

**Comment by cfinucane** [comment]
That's a clever work-around, but it does still break compatibility with the handlebars.js API, doesn't it?

**Comment by dontgitit** [comment]
Correct, it still breaks compatibility. 

As I mentioned, I don't think it's possible for it to be compatible in its current form, since helpers can only return a `CharSequence` from `apply`. For this to work properly, there needs to be an `applySubexpression` (in addition to `apply`) that returns `Object`, and is called instead of `apply` when the helper shows up as a subexpression tag. (Or simpler, `apply` needs to change to return `Object` instead of `CharSequence`)

**Comment by cfinucane** [comment]
I just noticed #484 is dealing with the same issue, so thought it'd link it in here too.

**Comment by dontgitit** [comment]
Ah nice, seems that's exactly what I was referencing. 

@jknack Any thoughts on if/when that might happen?

**Comment by jknack** [comment]
fixed in master. could you please compile and try it?

Also, invite you all to try: http://jooby.org

**Comment by jknack** [comment]
Guys, did any of you try it?

Thanks

**Comment by dontgitit** [comment]
Haven't tried it yet, was waiting for the next release.

**Comment by jknack** [comment]
Can you try this: https://jitpack.io/#jknack/handlebars.java/eb88ab72bc ?

Please try to compile, run your app and let me know if you found any issue related to this change #484 

Don't think so, but want to make sure

**Comment by dontgitit** [comment]
I can't seem to get `jitpack` to work for me; I tried a few different patterns. I'm using SBT, these are the urls it generates, and none of them seem to work.

`"com.github.jknack.handlebars.java" % "handlebars" % "eb88ab72bc"`: https://jitpack.io/com/github/jknack/handlebars/java/handlebars/eb88ab72bc/handlebars-eb88ab72bc.pom

`"com.github.jknack" % "handlebars" % "eb88ab72bc"`: https://jitpack.io/com/github/jknack/handlebars/eb88ab72bc/handlebars-eb88ab72bc.pom

`"com.github.jknack.handlebars.java" % "handlebars.java" % "eb88ab72bc117c4e2adf9f178374c46ba98f9f3d",`: https://jitpack.io/com/github/jknack/handlebars/java/handlebars.java/eb88ab72bc117c4e2adf9f178374c46ba98f9f3d/handlebars.java-eb88ab72bc117c4e2adf9f178374c46ba98f9f3d.pom
