### ISSUE TITLE
Add a combineResolver method to Context

### ISSUE THREAD

**Issue by oliverdain** [jknack/handlebars.java#490]
As per https://groups.google.com/forum/#!topic/handlebarsjava/50Iws-OSCbw, one almost always wants to **add** a resolver to the Context, not replace the default ones. As such a `combineResolver` method might be a handy addition.

Also, might be worth updating the docs. Most of the docs show a new resolver replacing the existing ones but don't mention that this will break things. Reading those docs I thought new contexts added to the stack would have the default resolvers so things like passing values to partials would work but that is not the case. For example, see https://jknack.github.io/handlebars.java/stack.html  or https://jknack.github.io/handlebars.java/jackson.html.

**Comment by jknack** [comment]
the new method is: ```push(ValueResolver... resolvers)```
