### ISSUE TITLE
Using a Java Map object as Template input

### ISSUE THREAD

**Issue by LachlanLindsay** [jknack/handlebars.java#491]
Is there anywhere I can find an example JSON or Java map being used to populate the template?

**Comment by jknack** [comment]
There is an example in the [README.md](https://github.com/jknack/handlebars.java#hello-handlebarsjava)

Just change your model to be a Hash. In the example is a plain string. For example:

```java
Handlebars handlebars = new Handlebars();

Map<String, Object> model = new HashMap<>();

model.put("name", "Lachlan");

Template template = handlebars.compileInline("Hello {{name}}!");

System.out.println(template.apply(model));
```

Prints:

```
Hello Lachlan!
```

**Comment by hartmut-ltd** [comment]
Hello,

how to populate for e.g. `Hello {{user.firstname user.surname}}!` ?

I tried 
```
Map<String, Object> user = new HashMap<>();
user.put("firstname", "Charles");
user.put("surname", "Dickens");
Map<String, Object> model = new HashMap<>();
model.put("user", user);
```
without success.

**Comment by jknack** [comment]
yea it should work, just make sure you use call apply with ```model```, like:

```System.out.println(template.apply(model));```

not with ```user```

```System.out.println(template.apply(user));```

**Comment by hartmut-ltd** [comment]
all working as it should, the issue was something else.. 
Many thanks though for helping to track down the issue by confirming the code above should work!

**Comment by jknack** [comment]
you're welcome!

Also, I invite you to try: http://jooby.org (if I didn't do it alreay) :)

**Comment by LachlanLindsay** [comment]
Thanks Very much this cleared up my problem!
