### ISSUE TITLE
Add ability to configure custom template resolution via HandlebarsViewResolver

### ISSUE THREAD

**Issue by lewisdawson** [jknack/handlebars.java#493]
Currently the `HandlebarsViewResolver` does not allow for fully custom template resolution due to the fact that it internally instantiates the `Handlebars` and `URLTemplateLoader`. Via inheritance, you can override the `createTemplateLoader()` or `createHandlebars()`, but this is a bit brittle -- especially if you don't want to use a `URLTemplateLoader`.

I will open a pull request shortly that will make this more configurable.

**Comment by lewisdawson** [comment]
In the spirit of trying to not introduce breaking changes with my pull request, I left the `createTemplateLoader()` function alone. I am curious if there was a specific reason why the `createTemplateLoader()` function returns an `URLTemplateLoader` object rather than the `TemplateInterface`? Any thoughts/reasons on that?

**Comment by jknack** [comment]
Hey, thanks! I should do this a long time ago... 

about ```createTemplateLoader```? No reason, can you change it?

ps: know you're a Spring user, but invite you to try: http://jooby.org. It is an easy to use, fast and scalable micro web framework. There is a handlebars module too: http://jooby.org/doc/hbs/

**Comment by lewisdawson** [comment]
@jknack I can definitely make that change. It will be a breaking change for anyone who's done any form of inheritance-based implementation on that class. Are you ok with that?

**Comment by lewisdawson** [comment]
@jknack BTW, Jooby is a cool little framework. Thanks for contributing that to the community! I'll keep it in mind for future projects.

**Comment by jknack** [comment]
Yea, let's do it. It is a minor change

**Comment by lewisdawson** [comment]
@jknack Got it. I'll add that change to the pull request within the next day or two. Once complete, would this go out in a release immediately or do you have a fixed date for the next release?

**Comment by jknack** [comment]
I would like to fix/review a few more issues, but honestly don't have time... so yea if you need it I can push a minor release.

**Comment by lewisdawson** [comment]
@jknack I've checked in the `TemplateLoader` change. If you'd be willing to push that, I'd much appreciate it. Thanks!
