### ISSUE TITLE
Empty list check inconsistent with js implementations

### ISSUE THREAD

**Issue by tbvh** [jknack/handlebars.java#495]
Ok, let me revoke this issue. :/
Turns out I was miss-informed by highest voted answer on that stackoverflow question. In fact the http://handlebarsjs.com/builtin_helpers.html#conditionals docs define the way it is implemented in handlebars.java.

The following was the reported issue, but it is not actually an issue:
> To check if a list is empty (e.g. in order to see if a 'ul' should be rendered), this is the way to go for javascript implementations[1]:
>
>    {{#if list.length}}
>
> However, this evaluates to `false` in handlebars.java, whether `list` is empty or not. 
> The workaround is to use:
> 
>     {{#if list}}
> 
> ~~But this would evaluate to `true` for javascript implementations, also for empty `list` (that is: `[] == true`)~~.
> 
> ~~To be consisted, it would be nice if handlebars.java could implement the `.length` operation and evaluate the returned 0 as `falsy`~~.
> 
> [1] http://stackoverflow.com/a/21611066/364401

**Comment by jknack** [comment]
I'm sorry, I didn't get the issue/error. Can you please clarify it?

Thanks

**Comment by tbvh** [comment]
Sorry I was too quick making this issue, it can be closed.

I updated the issue to indicate that I made a mistake with my understanding
of how an empty list should be handled in handlebars, because of a bad
answer on stackoverflow.
Turns out that there is no issue.

**Comment by msangel** [comment]
So is this supported?
