### ISSUE TITLE
Expressions with periods aren't resolved properly when saved via the AssignHelper

### ISSUE THREAD

**Issue by lewisdawson** [jknack/handlebars.java#496]
Here's an example that will be referred to:

```
{{#assign "my.language"}}en{{/assign}}
{{#assign "my.i18njsonpath"}}/language_{{my.language}}.json{{/assign}}

The resolved path is -- {{my.i18njsonpath}}
````

The AssignHelper saves the entire expression as a single String name. In the example above, the line:

```{{#assign "my.language"}}en{{/assign}}```

results in the value ("en") being inserted into the context's `data` Map under the String key "my.language" after the following line executes:

```
options.context.data(variableName, finalValue.toString().trim());
```

When the next helper evaluates the expression, it fails to resolve the expression `{{my.language}}`:

```
{{#assign "my.i18njsonpath"}}/language_{{my.language}}.json{{/assign}}
```

It fails to resolve properly because `Context#get(List<PathExpression>)` is attempting to resolve only the first part of the expression, `my`. This is due to the `PathExpressionChain` tokenizing the expression and only evaluating each token against the resolvers rather than the entire path. The resulting assignment for the "my.i18njsonpath" expression will be "/language_.json", not "/language_en.json" as you'd expect it to be.

This was introduced with the removal of [this](https://github.com/jknack/handlebars.java/commit/ddf047ffe545f742116e45fb36cd20c58b513666#diff-02b0b822a8380ccf6907976da030758cL542) section of code. In particular, the following lines:

```
String dataKey = key.charAt(0) == '@' ? key.substring(1) : key;
// simple data keys will be resolved immediately, complex keys need to go down and use a
// new context.
value = data.get(dataKey);
```

There are two options I can think of to fix this:

1. Add logic to the `Context#get()` function to attempt to evaluate the full path against all resolvers for the `model`, `extendedContext.model`, and `data` contexts.
1. Add logic to the `AssignHelper#apply()` to parse out the path keys and save each key as a separate entry that points to another set of keys -- this would form a tree data structure that could be walked down.

Do you have thoughts/ideas on how you'd prefer this to be fixed? The second option above seems like the slightly better option as that appears to be how you're assuming the data's stored already. Do you have any classes or structures already in place that handle that sort of logic?

**Comment by lewisdawson** [comment]
@jknack Do you have any thoughts on the best approach to fix this issue?

**Comment by jknack** [comment]
well, not sure this is problem... the assign helper was a community contribution and think ```path.prop```  should not be supported. The period is used to define complex/subpath expressions.

Also the correct way to do this is via escape id expression ```[my.language]```:

```
{{#assign "my.language"}}en{{/assign}}
{{#assign "my.i18njsonpath"}}/language_{{[my.language]}}.json{{/assign}}

The resolved path is -- {{[my.i18njsonpath]}}
```

The use of ```[]``` let you apply an "invalid" identifiers or try it as a single unit.

**Comment by lewisdawson** [comment]
@jknack I see your point that this syntax probably shouldn't be supported since it causes potential issues with complex path expressions if it's not escaped properly. Feel free to close this. Thanks!
