### ISSUE TITLE
Class property of type map not found

### ISSUE THREAD

**Issue by mashleyttu** [jknack/handlebars.java#499]
Hi, We recently switched from standard mustache to handlebars, and have discovered an issue that if a class has a property of type map and the class is passed to the Template#apply method the map properties are not available.

For example,

```
class HandlebarsData {
 private Map<String,Object> mapData;
 ...
}

HandlebarsData hd = new HandlebarsData();
Map<String,Object> m = new HashMap<String,Object>();
m.put("test","test");
hd.setMapData(m);

Handlebars hbs = new Handlebars();
Template tpl = hbs.compileInline(templateContent); //templateContent has {{m.test}}
String html = tpl.apply(hd);
```
property m is completely missing.
we verified this via {{#each this}}{{@key}} - {{@index}}<br>{{#each this}}{{@key}} - {{@index}}{{/each}}{{/each}} and if and unless statements in the template.

We are using the latest stable build 4.0.5.
Thanks for any advice you may offer.
Matt

**Comment by jknack** [comment]
Hi,

  There is no ```m``` in your example so ```m.test``` will print nothing.

  Try: ```{{mapData.test}}``` (assuming HandlebarsData has a getMapData method).

**Comment by mashleyttu** [comment]
Hi, Thanks for the quick reply. That is my mistake on the example. Our actual code is more like the following:

```
`public class T1CUser extends BaseEntity {
    private String firstName;
    private String lastName;
    private String email;
    ...
}

public class BaseEntity {
     protected Map<String,Object> mMetaData;
}

T1Cuser u = uD.getUserByEmail(u.getEmail());
....
url = url+"/"+resetCode;
Map<String,Object> m = new HashMap<String,Object>();
m.put("url", url);
u.setmMetaData(m);
...
Handlebars hbs = new Handlebars();
hbs.infiniteLoops(true);
Template t = hbs.compileInline(templateContent);
String html = t.apply(u);

//Content of templateContent above
<td colspan="2">Dear {{firstName}} {{lastName}},<br/><br/>
				Someone requested a password reset for {{email}}. Please click the link below to reset your password.
				<br/><br/>
				<a href="{{mMetaData.url}}">{{mMetaData.url}}</a>
				<br/><br/>
				If you didn't request a password reset, feel free to disregard this email.
			</td>
`
```

firstName, lastName, and email appear without an issue. mMetaData isn't available in the template but I have verified it is set in the user object when it is passed to t.apply.

Would this be because we do not have a proper getter/setter for mMetaData? We have setmMetaData and getmMetaData as opposed to setMMetaData and getMMetaData. Haven't looked into the apply method in much detail.

Thanks!
Matt

**Comment by jknack** [comment]
Exactly, that's is the problem two options:

1. use ```getMMetaData```

2. use a field value resolver:

```java
String html = t.apply(Context.newBuilder(u).push(FieldValueResolver.INSTANCE));
```

option ```#2``` will give you access to ```mMetaData```

**Comment by mashleyttu** [comment]
Hi,

Went with option #2 so we didn't have to refactor code. Needed to add a .build() after .push then everything worked out!

Thanks for your timely and excellent support!
Matt

**Comment by jknack** [comment]
Oh yea, I missed the ```.build``` call!

You're welcome and invite you to try: http://jooby.org
