### ISSUE TITLE
Each helper not iterating over rhino native arrays.

### ISSUE THREAD

**Issue by karanpradhan** [jknack/handlebars.java#500]
`
Handlebars.registerHelper("chunk",function(arr,size,options){

    var t = JSON.stringify(arr);
    var temp = JSON.parse(t);

    var newArr=[]

    while(temp.length) {
        newArr.push(temp.splice(0,size));
    }

    return newArr;
});
`

Is the helper I was invoking from my template with an array of objects. I was trying to iterate over the returned array with the help of an each helper. 

`
{{#each (chunk myObject.getArray 2) }}
{{this}}
{{/each}}
`

But in the output I see java memory string like org.mozilla.NativeArray* . I am using a Map and Field value resolver. Is there something which I am doing incorrectly.

Thanks.

**Comment by jknack** [comment]
Fixed in master.

I invite you to try http://jooby.org

Thanks
