### ISSUE TITLE
Performance issues with Partials

### ISSUE THREAD

**Issue by tonysparks** [jknack/handlebars.java#507]
I apologize ahead of time if I'm abusing Partials and should be using another feature.

I use Partials for two use cases:

1) Dynamic templating:
Example:
```
{{#ifeq @root.metadata.eventName "SomeEvent"}}
        {{> x_template}}
{{else}}
        {{#ifbegins @root.metadata.eventMessageVersion "2."}}
        {{> y_template}}
        {{/ifbegins}}
{{/ifeq}}
```
This use case works great.

2) Organizing and structuring my templates so that they are easier to read/maintain
Example:
```
<html>
   {{> header_template}}
   ...
   {{> footer_template}}
</html>
```

The latter use case comes at a performance cost.  Doing some debugging and performance test show that the embedded partials are recompiled each time (currently as designed) and this causes two problems 1) a ton of work for the GC 2) CPU time for compiling.

Would it be possible to either offer a caching option on the partial helper or add another helper for inlining templates?

Thank you,

Tony

**Comment by jknack** [comment]
did you use a template cache?

Also, even using the template cache there is some CPU time required to locate the template on disk/classpath... The cache helps to not compile the same template more than once.

There is a proposed change to improve the cache #425

**Comment by tonysparks** [comment]
I'm not sure how I would utilize the cache; more information would be great.

I took a look at the Partial class and it seems like it would need to take advantage of the cache.

Any how, I solved the problem by creating a new Helper:

```java
handlebars.registerHelper("inline", new Helper<Object>() {
            // I suppose I could use the TemplateCache here instead
            private Map<String, Template> cache = new ConcurrentHashMap<>(); 
            
            @Override
            public CharSequence apply(Object partial, Options options) throws IOException {
                if(partial == null) {
                    throw new IllegalArgumentException("must provide a partial name as a parameter");
                }
                
                String path = partial.toString();
                options.context.data(options.hash);
                
                if(!cache.containsKey(path)) {                                                                                
                    Template template = options.handlebars.compile(path);
                    cache.put(path, template);
                }
                
                Template template = cache.get(path);
                return new Handlebars.SafeString(template.apply(options.context));
            }
        });
```

Thanks!

**Comment by jknack** [comment]
Nice workaround. But you should add a cache for prod environments:

There are a few cache implementation inside the ```handlebars.jar``` but I strongly recommend you to use [Guava Cache](https://github.com/jknack/handlebars.java/tree/master/handlebars-guava-cache)

```java
Handlebars hbs = new Handlebars().with(new GuavaTemplateCache());
```

Tony, let me know if you have questions. Also, invite you to try: http://jooby.org

**Comment by tonysparks** [comment]
Thank you for the reply.

I believe there is either a bug in my helper or potentially a bug else where.

Given the following templates:

a.hbs
```
This is a test for: "{{@root.metadata.aggregateId}}"
{{{inline "b_inline" }}}
End test
```

b_inline.hbs
```
{{#@root.metadata}}
"metadata.aggregateId" : "{{aggregateId}}" 
"metadata.businessKey" : "{{businessKey}}"
{{/@root.metadata}}
```

With following hash:
```json
{"metadata":{"aggregateId":"ID:x0","aggregateType":"brett","businessKey":"favre"}}
```

I get the following results:
```
This is a test for: "ID:x0"

"metadata.aggregateId" : "ID:x0" 
"metadata.businessKey" : "favre"

End test
```

Which works as expected.

If I run the test twice using the same instance of Handlebars I receive:

With following hashes:
```json
{"metadata":{"aggregateId":"ID:x0","aggregateType":"brett","businessKey":"favre"}}
{"metadata":{"aggregateId":"ID:y0","aggregateType":"brett","businessKey":"favre"}}
```

I get the following results:
```
This is a test for: "ID:x0"

"metadata.aggregateId" : "ID:x0" 
"metadata.businessKey" : "favre"

End test

This is a test for: "ID:y0"

"metadata.aggregateId" : "" 
"metadata.businessKey" : ""

End test
```

Any ideas?

Thank you!

PS. Jooby looks pretty nice.  I'm a big fan of the Jax-ws/Jersey annotation way of doing things, I like you support both method and annotation route handlers.  I'm interested as to why you decided against implementing the JAX-WS annotations.  I'll have to do more digging.

**Comment by jknack** [comment]
Hi Tony,

 I can't reproduce it. Test is here: https://gist.github.com/jknack/7871efc635f3a8efc7bf7d5a0014f164

**Comment by tonysparks** [comment]
Not sure if you saw my comment on the gist; but from what I can see your test constructs a new handlebars instance per test, which doesn't stress the potential bug.  I was also able to reproduce this by using the TemplateCache and partials (i.e., it isn't just my inline helper).

**Comment by jknack** [comment]
Missed your comment, sorry. I answered there. Still works.

**Comment by andjarnic** [comment]
Handlebars hbs = new Handlebars().with(new GuavaTemplateCache());

fails for me. I have the 4.0.5 dependency version and it seems it needs a TemplateSource and Cache passed to the constructor.
