### ISSUE TITLE
Syntax when we have space in the JSON key

### ISSUE THREAD

**Issue by santhosh0101** [jknack/handlebars.java#508]
Hi jknack,

Thank you for your plugin.

We are trying to get the data of JSON like {{first name}}. You given syntax as {{[first name]}} but this we can't able to implement in our app. Is there any proper solution for this? 

Thanks & Regards,
Santosh Kumar

**Comment by jknack** [comment]
Hello,

 Thank you, for being a handlebars.java user :)

 Unfortunately, don't get the problem. Can you explain better with some example or reason of why the ```{{[first name]}}``` syntax doesn't work for you?

Thanks

**Comment by santhosh0101** [comment]
Hello,
           Thank you for responding. Actually we implemented mustache.java in our app. Now we migrated to Handlebars.java.
                     Previously they(mustache) allowed space in the JSON key. With normal syntax. All our customers are using that only. But now it is different in your plugin. We can't able to change that now. That's why we need proper solution to use in previous manner.

Thanks

**Comment by jknack** [comment]
Oh I see, there is a hacky way that you will have to test and probably improve:

```java
public class Workaround extends v4Test {

  @Override
  protected void configure(final Handlebars handlebars) {
    handlebars.registerHelperMissing(new Helper<String>() {
      @Override
      public Object apply(final String name, final Options options) throws IOException {
        // template to property path, so {{first name}} become [first name]
        String raw = options.fn.text();
        String path = raw.replace("{{", "[").replace("}}", "]");
        return options.context.get(path);
      }
    });
  }

  @Test
  public void test() throws IOException {
    shouldCompileTo("{{first name}}", $("hash", $("first name", "Santosh Kumar")), "Santosh Kumar");
  }
}
```

So, here handlebars try to find a ```first``` helper, the key is the ```missingHelper``` feature that works as fallback solution. There what I do is to convert the template expression from ```{{first name}}``` to ```[first name]``` and ask context to resolve the value.

As I said, this is a workaround and you might ran into troubles if there is an existing helper with the same name as the attribute... Still, don't think that is a real problem if you come from mustache.java but you will have to play.

Let me know if you have questions

**Comment by jknack** [comment]
Did you try it? Did it work?

**Comment by santhosh0101** [comment]
Hi,

      I tried it. But it showing error while using v4Test as well as Object apply. Is there any special jar file I have to include for this?


Thanks.

**Comment by jknack** [comment]
Sorry, that was just an example using the handlebars test framework. Here is the example in plain/raw handlebars:

```java
Handlebars handlebars = new Handlebars();
handlebars.registerHelperMissing(new Helper<String>() {
      @Override
      public Object apply(final String name, final Options options) throws IOException {
        // template to property path, so {{first name}} become [first name]
        String raw = options.fn.text();
        String path = raw.replace("{{", "[").replace("}}", "]");
        return options.context.get(path);
      }
    });
```

Give it a try!

**Comment by santhosh0101** [comment]
Hi,
      It is fine but i asked about it is not allowing Object apply. it showing **The return type is incompatible with Helper<String>.apply(String, Options)**. For reference i am giving my code here

public static Helper<String> HelperMissing(){
		return new Helper<String>(){
			@Override
		    public Object apply(final String name, final Options options) throws IOException {
				// template to property path, so {{first name}} become [first name]
		        String raw = options.fn.text();
		        String path = raw.replace("{{", "[").replace("}}", "]");
		        return options.context.get(path);
		    }
		};
	}

Thanks

**Comment by santhosh0101** [comment]
Hi,
      Its working fine when i changed Object to CharSequence and returning string. I don't know why it not accepted. 


Thanks

**Comment by jknack** [comment]
My bad, the snapshot/master version returns an Object while the latest Maven release returns a CharSequence. I will make a release soon.

In production environment, you need to use a [cache](https://github.com/jknack/handlebars.java#the-cache-system). I recommend you the [Guava Cache](https://github.com/jknack/handlebars.java/tree/master/handlebars-guava-cache)

Thanks.

**Comment by santhosh0101** [comment]
Hi,

       Thank you jknack. You gave me better solution for HelperMissing
exception. In the same way can you have any solution
for HandlebarsException?
                                       Because when we use some special
characters and international characters this error is coming.



Thanks & Regards,
Santosh Kumar

**Comment by jknack** [comment]
I need an example of when you got a HandlebarsException

**Comment by santhosh0101** [comment]
In JSON object key like {{first & name}}.  In the case of special characters...

**Comment by jknack** [comment]
Sorry, but there is no workaround for that in handlebars.java.

It is probably better to rewrite the template and then call handlebars via regex or similar. So you make sure every single {{...}} expression is translated to {{[...]}}. Think is the safe way and you don't need to the helper missing hack.
