### ISSUE TITLE
Trying to use @index from 1 got this error

### ISSUE THREAD

**Issue by techyrajeev** [jknack/handlebars.java#509]
could not find helper: 'math'
<td>{{math @index "+" 1}}. {{item}}</td>

Is math helper functions not available? is there any way to use index from 1 instead of zero?

**Comment by jknack** [comment]
did you figure it out, right? There is no ```math``` helper, but you are safe to use ```{{@index_1}}```

Also, I invite you to try: http://jooby.org

**Comment by techyrajeev** [comment]
I figured it out. I created a helper method to increment the index.

**Comment by techyrajeev** [comment]
@jknack It is working well. One thing I noticed helpers have a registerDecorators. What is the use of decorators here ?  Docs do not mention it.

**Comment by jknack** [comment]
Good, but yea you don't need a custom helper for +1 just use ````{{@index_1}}```

That's right there isn't good doc about decorators. It is for advanced users work with reference to handlebars.js is here #433 and here #442
