### ISSUE TITLE
Default templateCache in handlerbars-springmvc

### ISSUE THREAD

**Issue by ricardohbin** [jknack/handlebars.java#512]
The README.md says that the default templateCache is *NullTemplateInstance*, but since version 2.3.1, the default implementation in handlebars-springmvc is * HighConcurrencyTemplateCache* (as can seen in https://github.com/jknack/handlebars.java/compare/v2.2.3...v2.3.1#diff-011ad0775424ac2a36f02236812d76a5R122

**Comment by kaosx5s** [comment]
I just ran into this issue also - you can get around it by setting the ```HandlebarsViewResolver``` to use the null template cache during ```@PostConstruct```.

ex:
```java
    @Autowired
    HandlebarsViewResolver resolver;

    @PostConstruct
    protected void setupResolver(){
        resolver.getHandlebars().with(NullTemplateCache.INSTANCE);
    }
```
