### ISSUE TITLE
TypeSafeTemplate throws on toString, hashCode, and equals

### ISSUE THREAD

**Issue by kilink** [jknack/handlebars.java#514]
I think it would be nice if the proxy object returned by BaseTemplate.newTypeSafeTemplate did not throw on method calls such as toString, hashCode, and equals. In the very least, toString should behave normally, which would aid in debugging.

Guava actually has an [InvocationHandler](https://github.com/google/guava/blob/65e6bd2efb54b9f6a94de0771db698cea8d2a1ca/guava/src/com/google/common/reflect/AbstractInvocationHandler.java#L42) implementation that provides defaults for the above methods. I guess only the Guava cache package has a dependency on Guava, but it could serve as a reference at least.

I'm opening this issue before a PR to make sure there's support for this change. Thoughts?

**Comment by jknack** [comment]
Sure, will wait for your pull request.
