### ISSUE TITLE
The TypeSafeTemplate proxy and Java 8 default methods

### ISSUE THREAD

**Issue by kilink** [jknack/handlebars.java#515]
I had a case where I wanted to add some default methods to a TypeSafeTemplate sub-interface, but soon found that it would require the cooperation of the proxy implementation to detect and delegate to such default methods. There is a way to call default methods given just an interface, but it requires a bit of gymnastics and isn't particularly pretty.

Here's an example:

```java
interface UserTemplate extends TypeSafeTemplate<User> {

    UserTemplate setName(String name);

    UserTemplate setAge(int age);

    /* ... */

    default String render(User context) {
        try {
            return apply(context);
        } catch (IOException exc) {
            // Writing to a string shouldn't have caused an IOException...
            throw new UncheckedIOException("Unexpected exception", exc);
        }
    }

}

/* ... */

UserTemplate template = handlebars.compile("{{name}}").as(UserTemplate.class);
template.render(user);

```

If you think this would be useful, and worth the minor increase in LoC and complexity in the TypeSafeTemplate proxy implementation, I'll open a PR.

**Comment by jknack** [comment]
please do, open a pull request
