### ISSUE TITLE
Are partial/block helpers Handlebar.js compatible?

### ISSUE THREAD

**Issue by mAAdhaTTah** [jknack/handlebars.java#516]
This may be just a documentation issue, but in the documentation, you recommend using the `block` / `partial` helpers for template inheritance:

http://jknack.github.io/handlebars.java/reuse.html

We've been using these successfully when rendering from the BE, but we attempted to compile a template with it using Handlebars.js and it said the `partial` and `block` helpers weren't available. It _kinda_ looks like it should work fine with the new decorators/inline partials syntax, which were added in 4.0, but I'm not sure, and I don't want to change over all my templates just to find it won't work.

Would you recommend the new decorator-based inline partial syntax to achieve this same functionality? Have you (or anyone else) experienced this issue with compiling the templates with hbs.js as recommended? And lastly, if it does work, would you be open to updating the documentation to use the new syntax?

**Comment by jknack** [comment]
Yea the block/partial helpers were a workaround at that time.

Today? Think is better to go with decorators but I didn't try it. Can you?
Will be great if you can update the doc too.

Thanks.
