### ISSUE TITLE
Allow to chain escapers

### ISSUE THREAD

**Issue by ihommani** [jknack/handlebars.java#521]
Hi, 

I am using handlebar 4.0.5.

I wanted to know if the handlebars.java roadmap contains a feature allowing to chain escapers. 
Currently when I create a Template with escaper there is no possibility to specify several escapers. 
If I want to mix several escape policy I have to implement my own über escaper.

If I create a template as follow: 

`new Handlebars()
                    .with(MyPersonalEscapeStrategy)
                    .with(EscapingStrategy.CSV)
                    .registerHelper("join", JoinHelper())
                    .compileInline("...");`

MyPersonalEscapeStrategy will not be taken into account. Only the last specified escaper will be applied.

So like we have the possibility to chain Formater, It would be nice to add the possibility to chain escaper.

**Comment by ihommani** [comment]
Hi, 

Is this need irelevant ? Should I reformulate ?

**Comment by jknack** [comment]
sorry didn't get back to you.. I saw it then forgot.

I'm happy to add it if you send a pull request? Can you?

:)

**Comment by ihommani** [comment]
Hi, 

Yes I can :) .

**Comment by jknack** [comment]
awesome!

Also you're welcome to try http://jooby.org

**Comment by ihommani** [comment]
Yeah I noticed you advise it a lot :).
I will take a look :)

**Comment by jknack** [comment]
yea, sorry :)

It's just another chance/way to get more people/users
