### ISSUE TITLE
Helpers namespace

### ISSUE THREAD

**Issue by gahissy** [jknack/handlebars.java#525]
I'd like to fork the project to be able to add namespace to helpers and do something like : 
```hbs
 {{{nav.render 'main' }}
```
What'd be the steps to implement this feature ? Can you point me to the code to update ?
Thank you.

**Comment by jknack** [comment]
`nav.render` is a valid helper name, just need to register a helper with that name:

```java
Handlebars hbs = ...
hbs.registerHelper("nav.render", new Helper() {
 ...
});
```

**Comment by gahissy** [comment]
My bad. Thank you !

**Comment by jknack** [comment]
No problem.

Invite you to try http://jooby.org
