### ISSUE TITLE
Underscore in keys does not work

### ISSUE THREAD

**Issue by homeation** [jknack/handlebars.java#528]
If a key contains an underscore, the matching from the object does not work.
For example, `{{first_name}}` will not match an object with the property `String first_name;`

**Comment by jknack** [comment]
you must add a `field` value resolver or if you have a method named like that a custom method value resolver:

```java
Handlebars hbs = new Handlebars();

MyObject obj = ...;
Context ctx = Context.newBuilder(obj)
   .push(FieldValueResolver.INSTANCE)
  .build();

String rendered = hbs.compile(...).apply(ctx);
```
