### ISSUE TITLE
Setting HelperSource through springmvc

### ISSUE THREAD

**Issue by jiacona** [jknack/handlebars.java#535]
Adding a HelperSource through springmvc seems to be broken (or I'm just not doing it right). The relevant part of my spring `webmvc-config.xml` is 

```xml
<bean class="com.github.jknack.handlebars.springmvc.HandlebarsViewResolver" id="handlebarsViewResolver">
	<property name="helpers">
		<list>
			<bean class="helpers.NamesHelper" />
		</list>
	</property>
</bean>
```
Where `NamesHelper` is a HelperSource object with instance helper methods.

This gives the following exception:

> org.springframework.beans.TypeMismatchException: Failed to convert property value of type 'java.util.ArrayList' to required type 'java.util.Map' for property 'helpers'
>  nested exception is org.springframework.core.convert.ConversionFailedException:  Failed to convert from type java.util.ArrayList<?> to type java.util.Map<java.lang.String, com.github.jknack.handlebars.Helper>

I am using Spring 3.2.1 and Handlebars.java 4.0.5

**Comment by jiacona** [comment]
I've narrowed it down to this.

```
Invalid JavaBean property 'helpers' being accessed! Ambiguous write methods found next to actually used [public void com.github.jknack.handlebars.springmvc.Ha
ndlebarsViewResolver.setHelpers(java.util.List)]: [public void com.github.jknack.handlebars.springmvc.HandlebarsViewResolver.setHelpers(java.util.Map)
```

It seems the spring xml beans configuration cannot distinguish between `setHelpers(java.util.List)` and `setHelpers(java.util.Map)`. 

I changed the name of the `setHelpers(java.util.List)` method to `setHelperSources(java.util.List)` to remove the ambiguity

**Comment by jknack** [comment]
We just have a few projects with Spring but all them uses JavaConfig (not xml).

Our new project are built on top of http://jooby.org (have a look if you got 5 minutes)

Thanks for your pull!

**Comment by jiacona** [comment]
Thanks for the merge. I'd rather use JavaConfig for spring, but I'm working on a legacy project so need to use xml config. Any thoughts on when you might do a release? It would be great if I could get this from maven central.

Jooby looks quite interesting, I'll keep it in mind for future projects.

**Comment by jknack** [comment]
I like to group a few issues before making a release... This is the first issue for `4.0.7` so don't expect any release soon, sorry.

I can release `4.0.7-SNAPSHOT` to sonatype snapshots: https://oss.sonatype.org/content/repositories/snapshots/ 

does it work for you?

**Comment by jiacona** [comment]
Ok, no worries. A snapshot release would be great though. Thanks!

**Comment by jknack** [comment]
Snapshot ready.

**Comment by jknack** [comment]
@jiacona thanks! Please give it a star (if you don't already)
