### ISSUE TITLE
Escaping square brackets [ ] 

### ISSUE THREAD

**Issue by chipshorter** [jknack/handlebars.java#547]
I've been unable to find a way of getting square brackets to render in my template with handlebars.java. 

e.g.  create table [{{table_name}}] -> create table [employees]

It seems to be supported in handlebars.js, as I've been able to test it successfully on http://tryhandlebarsjs.com. 

Is there some way to escape square brackets in handlebars.java?

**Comment by jknack** [comment]
hmm something might be happening, just ran a quick test and seems OK. Look:

```java
package com.github.jknack.handlebars.issues;
import java.io.IOException;
import org.junit.Test;
import com.github.jknack.handlebars.v4Test;

public class Hbs547 extends v4Test {

  @Test
  public void squarebrackets() throws IOException {
    shouldCompileTo("create table [{{table_name}}]", $("hash", $("table_name", "employees")), "create table [employees]");
  }
}
```

**Comment by chipshorter** [comment]
Please accept my apologies, you are correct. There was an error elsewhere in our code.

**Comment by jknack** [comment]
No problem Chris, glad you found and fixed it.

Also, I invite you to try http://jooby.org
