### ISSUE TITLE
escape sequence prevents nesting further variables: \{{ {{foo}} }} gives an Exception

### ISSUE THREAD

**Issue by precchia** [jknack/handlebars.java#558]
the template \{{ {{foo}} }} renders to {{ bar }} in handlebars.js
In handlebars.java it gives a HandlebarsException (found '\').
Shouldn't it be handled the way handlebars.js does?

The reason for the Exceptoin is because, apparently, varEscape searches for a full variable to escape completely (so e.g. \{{foo}} )

Can't the 'escape sequence detection' (varEscape) just escape the opening tag?
This way the sequence in question could be parsed as expected?

I've actually tested it, and it seems like it doesn't break any existing test

**Comment by jknack** [comment]
Try it in handlebars.js 4.0.3 and got:

```
Error(s): Error: Parse error on line 1: {{ {{foo}} }} ----^ Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'OPEN'
```
