### ISSUE TITLE
The following contruct: {{{{noop}}}}{{ escaped() }}{{{{/noop}}}} results in an error

### ISSUE THREAD

**Issue by precchia** [jknack/handlebars.java#559]
Provided a 'noop' helper is registered:

		// {{{{noop}}}}
		handlebars.registerHelper("noop", new Helper<Object>() {
  		public Object apply(Object obj, Options options) {
				Buffer buffer = options.buffer();
				buffer.append(options.fn());
				return buffer;
			}
		})

The following contruct:

{{{{noop}}}}
{{ escaped() }}
{{{{/noop}}}}

is supposed to output the raw content inside noop:

{{ escaped() }}

(plus or minus spaces...)

Instead of that it issues an error:

com.github.jknack.handlebars.HandlebarsException: inline@6f992137:1:23: found: ')', expected: 'id'
{{{{noop}}}}{{ escaped() }}{{{{/noop}}}}
                       ^

**Comment by jknack** [comment]
There is no `escaped` helper in handlebars.java and `escaped()` syntax is not supported either.
