### ISSUE TITLE
compex condition

### ISSUE THREAD

**Issue by amiroshn** [jknack/handlebars.java#561]
`<tr><td colspan="2" class="subsectionHeading">Function and Provider Speciality</td></tr>
  {{#if function}}<tr><td class="labelCellIndent-1">Function:</td><td class="valueCell">{{function}}</td></tr>{{/if}}
   {{#if function-code}}<tr><td class="labelCellIndent-1">Function Code:</td><td class="valueCell">{{function-code}}</td></tr>{{/if}}`

I have these 3 rows. Is there any way to hide first one if conditions in second and third are FALSE?

Thank You.

**Comment by jknack** [comment]
yes, with a custom helper.
