### ISSUE TITLE
Some helpers don't work jknack engine

### ISSUE THREAD

**Issue by WilliamHeiderman** [jknack/handlebars.java#563]
This helper returned an error when I ran it through the jknack engine. As I understand it the wrapper can only translate so much of javascript into java. Is there a list of gotchas somewhere that we could use to avoid errors in the future? For example, window.foo doesn't function in jknack.

Handlebars.registerHelper('chunker', function(context, rows, elem, className, options) {
	var fn = options.fn,
	    i = 0,
	    chunk = '',
	    output = '',
	    data;
    if (options.data) data = Handlebars.createFrame(options.data);
    function isInt(n) {
        return n === +n && n === (n|0);
    }   
    function execIteration(field, index, last) {
        if (data) {
            data.key = field;
            data.index = index;
            data.first = index === 0;
            data.last = !!last;
        }
        chunk += fn(context[field], {
            data: data,
            blockParams: [context[field], field]
        });

        var chunkStop = (index + 1) / rows;
        var num = isInt(chunkStop);
        if (num) {
            output += "<"+elem+" class="+className+">" + chunk + "</"+elem+">";
            chunk = "";
        }
    }
    if (context && typeof context === 'object') {
        var priorKey;
        for (var key in context) {
            if (key !== undefined) {
                if (priorKey !== undefined) {
                    execIteration(priorKey, i - 1);
                }
                priorKey = key;
                i++;
            }
        }
        if (priorKey !== undefined) {
            execIteration(priorKey, i - 1, true);
        }
    }
    if (chunk !== "") {
        output += "<"+elem+" class="+className+">" + chunk + "</"+elem+">";
    }
    return output;
});

**Comment by jknack** [comment]
Internal handlebars.js API is not supported (Handlebars.createFrame)
