### ISSUE TITLE
Each, else not working

### ISSUE THREAD

**Issue by jfbrennan** [jknack/handlebars.java#574]
The handlebars.js docs say (see http://handlebarsjs.com/builtin_helpers.html#iteration):

You can optionally provide an `{{else}}` section which will display only when the list is empty.
```
{{#each paragraphs}}
  <p>{{this}}</p>
{{else}}
  <p class="empty">No content</p>
{{/each}}
```

This does not seem to be working in Handlebars.java. I'm using Handlebars.java version 2.0.0

**Comment by dontgitit** [comment]
> I'm using Handlebars.java version 2.0.0

That might be your issue, that's a really old version. See if it works in v4+

**Comment by dontgitit** [comment]
@ccleve works for me on `4.0.6`. Make sure is `paragraphs` is empty (`{"paragraphs": []}`) rather than `null` or not defined

**Comment by ccleve** [comment]
@dontgitit Yes, you are correct, that was exactly my error. 

Perhaps the else clause should be invoked when paragraphs is null.
