### ISSUE TITLE
@index, @first, @last not working when using Jackson2 helper

### ISSUE THREAD

**Issue by srigor** [jknack/handlebars.java#577]
Using: handlebars.registerHelper("json", Jackson2Helper.INSTANCE);
Version: 4.0.6 of jknack/handlebars

With the following sample test json:
```json
"notification_registration_data": {
    "registrations": [
      {
        "id": 321,
        "language_cd": "ENGLISH",
        "notification_method_cd": "PHONE",
	"pin": "3847"
      },
      {
        "id": 322,
        "language_cd": "ENGLISH",
        "notification_method_cd": "PHONE",
	"pin": "4636"
      },
      {
        "id": 323,
        "language_cd": "ENGLISH",
        "notification_method_cd": "PHONE",
	"pin": "8893"
      }
    ]
  }
```
Attempting to loop through array for pins in my handlebars template as such:
`"pin_codes": [{{#each notification_registration_data.registrations}}"{{pin}}"{{#unless @last}},{{/unless}}{{/each}}]`

Gives me this output:
`"pin_codes": ["3847","4636","8893",]`

It's as if @last is never true in the EachHelper because that last comma in the output should not be there. The same thing happens when trying to use @first. Attempting to print {{@index}} in the handlebars template returns nothing in the output. Not sure if this is just an issue using the Jackson2 helper or if this is an issue accross the board when looping over json arrays using #each.

**Comment by sankotm** [comment]
I have the same problem using JacksonHelper.

**Comment by srigor** [comment]
I forgot to update this, but I was able to resolve the issue by adding more resolvers in the Context:
```
Context context = Context
                .newBuilder(jsonData)
                .resolver(JsonNodeValueResolver.INSTANCE,
                        JavaBeanValueResolver.INSTANCE,
                        FieldValueResolver.INSTANCE,
                        MapValueResolver.INSTANCE,
                        MethodValueResolver.INSTANCE)
                .build();
```
I originally was only using the JsonNodeValueResolver. After adding the other resolvers above, looping through the array in json within a template worked as expected using @index, @first, @last, etc.

**Comment by sankotm** [comment]
right, it's pretty strange that adding resolver makes @first/@last work. and for reference it's MapValueResolver.INSTANCE that makes it work.
