### ISSUE TITLE
Compatibility with Handlebars.js

### ISSUE THREAD

**Issue by izeye** [jknack/handlebars.java#580]
I'm working on a project sharing Handlebars.js templates between JavaScript-based system and Java-based system.

With Java-based system, I'm considering using this library.

Is Handlebars.java v4.0.6 100% compatible with Handlebars.js v4.0.6 from the template rendering point of view?

I read "Differences between Handlebars.java and Handlebars.js" section and it looks ignorable for me. And I saw "Handlebars.js Compliant" but I couldn't be sure that this is true between the latest versions.

**Comment by jknack** [comment]
it is compatible but I can't say it is 100%
