### ISSUE TITLE
Cannot use external data store for Context data map

### ISSUE THREAD

**Issue by pwaligora** [jknack/handlebars.java#586]
Context.data is hard coded to be a HashMap. This makes it difficult to use external data structures that an organization might use.

Context.data should be an interface type which supports get, put, putAll, and clear. Constructors should be defined that allow for the user to supply their own instance of the interface, or default to a standard one which uses HashMap.

A proposed interface would be:
public interace ContextDataMap {
    public Object get(String name);

    public void put(String name, Object value);

    public void putAll(Map<String, ?> attributes);

    public void clear();
}

**Comment by jknack** [comment]
There is a contract for custom data sources: https://github.com/jknack/handlebars.java#using-the-valueresolver
