### ISSUE TITLE
precompile helper dosen't support 'partial with parameter' 

### ISSUE THREAD

**Issue by daewooLeeNy** [jknack/handlebars.java#596]
Hi,
I am using the version v4.0.6.
Precompile helper does not working partial with parameters.
similar to https://github.com/jknack/handlebars.java/issues/350

Refer to test case in https://github.com/jknack/handlebars.java/blob/1f6c48e606dc1303d1e92a0a0eaa94120eba64fd/handlebars/src/test/java/com/github/jknack/handlebars/PrecompileHelperTest.java.

I change some template for partial with parameter.
```
  URLTemplateLoader loader = new MapTemplateLoader()
      .define("input", "Hi {{this}}!")
      .define("root", "{{> partial/child root=this name=\"Han\"}}")
      .define("partial/child", "CHILD!!! {{root}}'s child {{name}}");
```

Below generated precompile context with HandlebarsJava:
```
(function() {
  var template = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    var stack1;

  return ((stack1 = container.invokePartial(partials["partial/child"],depth0,{"name":"partial/child","data":data,"helpers":helpers,"partials":partials,"decorators":container.decorators})) != null ? stack1 : "");
},"usePartial":true,"useData":true});
  var templates = Handlebars.templates = Handlebars.templates || {};
  templates['root'] = template;
  var partials = Handlebars.partials = Handlebars.partials || {};
  partials['root'] = template;
})();
```

Some different to precompile context with nodeJS.
look at the 'hash' argument in container.invokePartial()
```
(function() {
        var template = Handlebars.template, templates = Handlebars.templates = Handlebars.templates || {};
        templates['root'] = template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
            var stack1;

            return ((stack1 = container.invokePartial(partials["partial/child"],depth0,{"name":"partial/child","hash":{"name":"Han","root":depth0},"data":data,"helpers":helpers,"partials":partials,"decorators":container.decorators})) != null ? stack1 : "");
        },"usePartial":true,"useData":true});
    })();
```

**Comment by ggggl** [comment]
I have run into the same issue - is this something that is possibly being looked into?  

Possibly related, I am also having issues getting a partial to recognize parent context references.  Considering that is also in play around the same bit of code that calls invokePartial(), thought it might be worth mentioning.

thanks!
