### ISSUE TITLE
Accessing a list from JSON using dotted notation

### ISSUE THREAD

**Issue by bajrangg** [jknack/handlebars.java#599]
Hi jknack - I am trying to use handlebars for my templating solution. Thank you for the work you have done!

My question is on accessing the  values using dotted notation. I am able to access when they are straight values, however when it comes to list - it does not go through.

Example:
{
	"id": {
		"a": "A",
		"b": [{
			"b1": "B1"
		}, {
			"b2": "B2"
		}],
		"c": "C"
	}
}
 
I can access {{id.a}}.
How do I access the values in array of b.

Appreciate your help!

**Comment by jknack** [comment]
Try: `{id.b.[0].b1}`

See https://github.com/jknack/handlebars.java/issues/150

**Comment by bajrangg** [comment]
Wow...that is one of the quickest response I have received.

What if there are multiple items? Is there a way not to hard code the index?
