### ISSUE TITLE
Unable to use Handlebars.createFrame in javascript helper

### ISSUE THREAD

**Issue by frankcs** [jknack/handlebars.java#601]
First of all, thanks for all the work put into this project. It's very much appreciated.

Here is my issue: I'm trying to migrate all my helpers code to javascript to avoid having duplicates in my frontend code and in my java server code. I'm facing a problem with `Handlebars.createFrame` in a helper that creates a new context. `Handlebars.createFrame` is not available in the `Handlebars` global variable defined in `helpers.rhino.js`. Can we have this functionality added?

**Comment by frankcs** [comment]
I've found a workaround for `Handlebars.createFrame` problem. I added that function to the `helpers.js` I'm providing with the helpers definitions. Is not ideal but it works. The problem is now that calling `options.fn` with two parameters is failing.

My implementation is based on this handlebars docs example (Third code snippet within has-arguments section):

http://handlebarsjs.com/block_helpers.html#hash-arguments

Any ideas?

**Comment by jknack** [comment]
Show me what are you trying to do and probably can help you to write something that works in browser and server.

 .createFrame isn't an option. It is part of the implementation details of handlebars.js and it is practical impossible to replicate that in handlebars.java

**Comment by frankcs** [comment]
Thanks for your reply. No worries, I can make my helper be aware of the environment and execute the proper instruction, but I was hoping not having to do that. The idea behind this is that the same helper would work seamlessly. I'll probably try to make some modifications to `RhinoHandlebars` and  `helpers.rhino.js` and see what happens. I'll issue a PR if get it to work. Thanks again.
