### ISSUE TITLE
Can java pojo's be used on handlebars (mustache) template?

### ISSUE THREAD

**Issue by HugoMario** [jknack/handlebars.java#602]
I'm trying to changes a project template engine from mustache to handlebars, but it seems the POJO's used for mustache doesn't work the same way for handlebars, i've been reading some issues and it seems like #491 and it seems this objects needs to be converted to map.

I'm wondering if migrating to Map's is the only way or if it's possible to use POJO's and i'm missing something.

This is a template example:
https://github.com/swagger-api/swagger-codegen/blob/3.0.0_enhancements/modules/swagger-codegen/src/main/resources/Java/pojo.mustache

**Comment by jknack** [comment]
don't over thinking :)

We do support pojo, javabeans, etc..

```
Template template = handlebars.compile("person")

template.apply(new Person("Hugo", "Mario"));
```
Then from template you can do:

```
Hi {{firstName}} {{lastName}}
```

Thanks

**Comment by HugoMario** [comment]
thanks @jknack actually the pojo's didn't have getter & setters once included it worked fine.
