### ISSUE TITLE
FormatterChain only work for the first variable

### ISSUE THREAD

**Issue by daneps** [jknack/handlebars.java#609]
Custom formatters only work for the first variable. The chain is never reset at Variable.formatAndEscape, only the first variable is formatted with the custom formatter, and subsequent variables are output as value.toString(); Not sure where the best place to reset the formatter chain would be.
Example test:

  static final long now = System.currentTimeMillis();

  @Override
  protected void configure(final Handlebars handlebars) {
    handlebars.with(new Formatter() {

      @Override
      public Object format(final Object value, final Chain chain) {
        if (value instanceof Date) {
          return ((Date) value).getTime();
        }
        return chain.format(value);
      }

    });
  }

  @Test
  public void resolveThis() throws IOException {
    shouldCompileTo("time is {{this}}{{this}}", new Date(now), "time is " + now+now);
}

**Comment by jknack** [comment]
Fixed in #548
