### ISSUE TITLE
String Helpers missing from Built in Helper

### ISSUE THREAD

**Issue by mazipan** [jknack/handlebars.java#617]
from this part [link](https://github.com/jknack/handlebars.java#helpers), Handlebars already developing some nice helpers like:
```
with
each
if
unless
log
block
partial
precompile
embedded
i18n and i18nJs
string helpers
```

but unfortunately some of helpers are not included by default in Handlebars object.
I already debug to see which helpers already exist in handlebars itself, and only got this helpers:
```
with----com.github.jknack.handlebars.helper.LookupHelper@3c5d183
unless----com.github.jknack.handlebars.helper.LogHelper@471b7c9c
precompile----com.github.jknack.handlebars.helper.BlockHelper@39cf7f3c
if----com.github.jknack.handlebars.helper.EmbeddedHelper@25df95b
partial----i18nJs
each----i18n
``` 

Need to add `string helpers` as built-in helpers

**Comment by jknack** [comment]
Yes, this was intentional. You need to manually added them

**Comment by mazipan** [comment]
So, maybe will good for Us if you tell about that in the docs.
Because I think will be missleading with current condition.
