### ISSUE TITLE
HandlebarsException compileInline(html)

### ISSUE THREAD

**Issue by hadesgrid** [jknack/handlebars.java#621]
Hello I wonder if some one could help me please.

I am having the following error when trying to compile with the following method

template = handlebars.compileInline(html);
the error is :

{code}
Exception in thread "main" com.github.jknack.handlebars.HandlebarsException: inline@468cc751:628:179: found: '">Guardar PDF</a></li> \n'
         <li><a href="{{ibeUrl " api portal checkout attachmentdownload.do?bookingmanagement downloadtype="confirmation"}}&bookingSearch/reference={{SuperPNR_ID}}"" class="ico-pdf">Guardar PDF</a></li> 
{code}

i don now what to do

many thanks in advance
Ana
``

**Comment by jknack** [comment]
Hi, can you please post the template you try to compile along with the full stacktrace?

Thanks
