### ISSUE TITLE
Custom interpolation symbol

### ISSUE THREAD

**Issue by marcinczeczko** [jknack/handlebars.java#623]
Is it possible to use custom interpolation symbol ?
E.g.
Use `<[`, `]>` instead of `{{`, `}}`

I'm asking because I'm trying to mix the server side rendered mustache templates that are then used as angular view, that uses same interpolation symbols as handlebars, so wanted to avoid wrong results

**Comment by jknack** [comment]
```
Handlebars hbs = new Handlebars();
hbs.setStartDemiliter("<[");
hbs.setEndDemiliter("]>");
```

**Comment by marcinczeczko** [comment]
@jknack - thanks !
