### ISSUE TITLE
i18n helper - use html tags in translation strings

### ISSUE THREAD

**Issue by schmkr** [jknack/handlebars.java#636]
hi there,

thanks a lot for this amazing library. It's getting better every release!

Is there a way to use html tags in translation strings, with the tags getting escaped? For example, in a template:

```html
<p>{{i18n "contact.support"}</p>
```

and `messages.properties` contains:

```
contact.support=Contact us at <a href="mailto:support@example.com">support@example.com</a>
```

renders the translated string escaped.

Is there a way to tell the i18n-helper to not escape (some) translation strings?

**Comment by jknack** [comment]
Yes!

    {{& i18n "contact.support"}

**Comment by schmkr** [comment]
Awesome, thanks! That works like a charm
