### ISSUE TITLE
Extending HandlebarsViewResolver

### ISSUE THREAD

**Issue by erikahlswede** [jknack/handlebars.java#638]
I have a use case where I want to extend HandlebarsViewResolver to compile the template inline, rather than via a template path:

Here is an example of the method. 

Psuedo-code:

```
    protected AbstractUrlBasedView configure(HandlebarsView view) throws IOException {
        String path = view.getUrl()
        String templateContent = getTemplateFromApi(path);
        try {
            view.setTemplate(this.handlebars.compileInline(path));
            view.setValueResolver(this.valueResolvers);
        }
        ...
        return view;
    }
```

The problem is that the `HandlebarsView.setTemplate` , and `HandlebarsView.setValueResolvers` are package private.

I'd rather not have to re-implement an entire view resolver to override the specific `HandlebarsView` logic.

Do you see a reason why the following changes could not be made?

`HandlebarsView.setTemplate` go from `package-private` to `public`
`HandlebarsView.setValueResolver` go from `package-private` to `public`
` private HandlebarsView.getValueResolvers` go from `non-existent` to `existent`

The other way I see this solvable is to change the signature of 
```protected AbstractUrlBasedView configure(HandlebarsView view) throws IOException```

to 

```protected AbstractUrlBasedView configure(AbstractUrlBasedView view) throws IOException```
 and cast to `HandlebarsView` inside `configure`.

This way I believe I can override `configure` and shim in my own version of a `AbstractTemplateView`

**Comment by jknack** [comment]
Sorry, for my late response. Have no problem with these changes:

```
HandlebarsView.setTemplate go from package-private to public
HandlebarsView.setValueResolver go from package-private to public
private HandlebarsView.getValueResolvers go from non-existent to existent
```

Can you send a pull request?

Thanks

**Comment by erikahlswede** [comment]
Will do.
