### ISSUE TITLE
Set ObjectNode to template(.hbs)

### ISSUE THREAD

**Issue by nobuoonodera** [jknack/handlebars.java#648]
Hi guys,

As title, I want set `ObjectNode` as value. Previous version, following template is working. However, it is invalid from `4.0.3`. `JsonNodeValueResolver` is used as resolver.

*Template.json.hbs*
`
{
 "elem": {{node}}
}
`

*Context*
`
{
  "node": {
    "nest":"value"
  }
}
`

Then, the result is following. Is this expected behavior? As a matter of fact, I don't know the spec of this resolver. However, I suspect this is a bug. From `4.0.3`, the instance of `ObjectNode` is always converted to `Map`.

`
{
 "elem": {
    nest="value"
  }
}
`

**Comment by jknack** [comment]
don't think we change anything here, but probably we upgrade jackson (not sure).

Anyway, you shouldn't rely in the `.toString` method. Instead, you should use the `json` helper

```
{ "elem": {{json node}} }
```

**Comment by nobuoonodera** [comment]
It works with `json` helper. Thank you. I leave my code for other developers.

*code*
`
handlebars.registerHelper("json", Jackson2Helper.INSTANCE).compile(templatePath).apply(context);
`

*Template.json.hbs*
`
{ "elem": {{#json node}}{{/json}} }
`

**Comment by jknack** [comment]
Cool!

Also, this works too:

```
{ "elem": {{json node}} }
```

(shorter)
