### ISSUE TITLE
Handlebars Server

### ISSUE THREAD

**Issue by jknack** [jknack/handlebars.java#65]
Handlebars.java users want a handlebars standalone and easy to use server:
- The server require a working dir.
- The working dir have all the handlebars templates
- Each template (home.html) can specify a json file with data (home.js)
- The handlebars server will server any static resource, like *.css, *.png, etc.

Example:

**mydir/home.html**:

``` html
<ul>
  {{#items}}
   {{name}}
  {{/items}}
</ul>
```

**mydir/home.js**:

``` js
{
  items: [
    {
      name: "Handlebars.java rocks!"
    }
  ]
}
```

**Running the server**:

```
java -jar handlebars-proto-*.jar -dir mydir
```

**Open a browser and type**:

```
http://localhost:6780/home.html
```

**Comment by janacm** [comment]
Is it possible to register a helper while running this server?

**Comment by jknack** [comment]
not today, no.

**Comment by janacm** [comment]
Is there any limitations with nesting templates?

**Comment by janacm** [comment]
Ah, looks like the Partials section is what I was looking for. 

Also, what would the "Blog" class contain, in your example under Helper Sources you have the following:

```
 public String blog(Blog blog, Options options) {
    return options.fn(blog);
  }

```

But what does this Blog class need to implement?
