### ISSUE TITLE
Load Template From String

### ISSUE THREAD

**Issue by tpurcell** [jknack/handlebars.java#651]
I have a need to load existing handlebar templates for a database. I load them, compile them and store them in a Map.  This works fine for simple templates but falls apart when templates contain partials. 

I've tried implementing TemplateLoader but sourceAt returns a TemplateSource which is the location of the template not the template.

Any thoughts on how to approach this?

**Comment by jknack** [comment]
Hi,

 Yea, you need a `TemplateLoader`. I wrote a map base implementation for tests: https://github.com/jknack/handlebars.java/blob/master/handlebars/src/test/java/com/github/jknack/handlebars/MapTemplateLoader.java

**Comment by tpurcell** [comment]
Okay, that did the trick. Thanks
Would it make sense to put MapTemplateLoader in main as opposed to test to make this capability more obvious?
