### ISSUE TITLE
Problem on using Handlebars.java Helper registration on Google Appengine local devserver

### ISSUE THREAD

**Issue by mpoehler** [jknack/handlebars.java#652]
I get a NPE on the Google Appengine local devserver when register a Helper. The deployed app works fine, and also if you execute the code in a test everything works as expected. Only in the local devserver a NPE is comming up. 

To show the error I adopted the [appengine quick-start app and added a servlet using handlebar.](https://github.com/mpoehler/hbs-test) You can just clone to reproduce the NPE locally.

Doing something like
```
public static String createWithHandlebar() throws Exception {
      Handlebars handlebars = new Handlebars();
      File helperPath = new File(HelloAppEngineHbs.class.getResource("/helpertest.js").getPath());
      handlebars.registerHelpers(helperPath);  // <-- this is where NPE is thrown
      Template template = handlebars.compileInline("Hello {{this}}!");
      return template.apply("Handlebars.java");
  }
```

results in 
```
java.lang.NullPointerException
	at com.github.jknack.handlebars.helper.DefaultHelperRegistry.engine(DefaultHelperRegistry.java:279)
	at com.github.jknack.handlebars.helper.DefaultHelperRegistry.registerHelpers(DefaultHelperRegistry.java:188)
	at com.github.jknack.handlebars.helper.DefaultHelperRegistry.registerHelpers(DefaultHelperRegistry.java:168)
	at com.github.jknack.handlebars.Handlebars.registerHelpers(Handlebars.java:688)
	at com.example.appengine.java8.HelloAppEngineHbs.createWithHandlebar(HelloAppEngineHbs.java:40)
	at com.example.appengine.java8.HelloAppEngineHbs.doGet(HelloAppEngineHbs.java:24)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
```

Snippet from `DefaultHelperRegistry` where the NPE occurs: 
```
private ScriptEngine engine() {
    synchronized (this) {
      if (this.engine == null) {
        this.engine = new ScriptEngineManager().getEngineByName("nashorn");
        this.engine.put("Handlebars_java", this);  // <-- NPE here!
        Throwing.run(() -> engine.eval(HELPERS_ENV));
      }
      return this.engine;
    }
  }
```

Which is possibly related to that issue: https://github.com/GoogleCloudPlatform/app-gradle-plugin/issues/160 , which indicates that there should be a `null` in the `ScriptEngineManager` constructor. But I have no clue, what it means. I will also add this to the Issue in app-gradle-plugin.

**Comment by jknack** [comment]
Latest handlebars.java requires Java 8+ which comes with `Nashorn` JavaScript Engine.

Your app engine server run in an older JVM, that is why there is no `nashorn`. You have two options:

- upgrade app engine to use Java 8
- downgrade handlebars.java to 4.0.x (this version uses Rhino instead of Nashorn)

**Comment by edouardmercier** [comment]
From my experience, even when using a JVM v8 for running a local GAE server, the thread context `ClassLoader`, accessible via `Thread.currentThread().getContextClassLoader()`, is an `com.google.appengine.tools.development.IsolatedAppClassLoader` created by the GAE framework, which is unable to load the `nashorn` `ScriptEngineManager` properly.

And resorting to the previously mentioned work-around, which consists in using the `(new ScriptEngineManager(null)).getEngineByName("nashorn")` does not solve the issue, and causes a `ClassCastException`. I've tried to cook a mix of context `ClassLoader` between the default one, and the `ClassLoader.getSystemClassLoader()`, with no luck.

Is someone by Google, who understand the restrictions imposed by the `com.google.appengine.tools.development.IsolatedAppClassLoader` can shed some light on this, this would be great.
