### ISSUE TITLE
Loading templates in modularized projects

### ISSUE THREAD

**Issue by fwgreen** [jknack/handlebars.java#663]
Once I add `module-info.java` to a project, Handlebars loses track of the template.  Please consider adding some sort of `ModulePathTemplateLoader`.

**Comment by jknack** [comment]
For me it should work as long as you expose/export the package with templates, not familiar with Java 9 (yet).

Can you provide more details with an example? What the ModulePathTemplateLoader would do?

Thanks

**Comment by fwgreen** [comment]
I'm sorry.  It seems my problem stems from not understanding how [resources are read from within modules](https://stackoverflow.com/questions/46861589/java-9-jigsaw-accessing-resource-files-from-external-modules).  I needed to move the templates out to the project root.
