### ISSUE TITLE
i18n has issue parsing results with single quotes before the arguement

### ISSUE THREAD

**Issue by hoffbeam** [jknack/handlebars.java#684]
With the following handlebar code

{{i18n "hello" "banana" }}

I will get the following outputs

hello=hola {0}!  = hola banana (correct)
hello= hey's hola {0}!  = hey's hola {0}! (incorrect)
hello=hola {0}! hey's = hola banana hey's (correct)

**Comment by hoffbeam** [comment]
my bad... looks like this is an issue with i18n

**Comment by jknack** [comment]
Seems we need to escape: https://stackoverflow.com/questions/17544794/escaping-single-quotes-for-java-messageformat

    hey''s hola {0}!
