### ISSUE TITLE
OWASP vulerability with included js file (can you please upgrade js file version to the latest?)

### ISSUE THREAD

**Issue by alexmnyc** [jknack/handlebars.java#738]
File Path: /Users/x/.gradle/caches/modules-2/files-2.1/com.github.jknack/handlebars/4.1.2/62b172b650bdecdb647c7538c4faf140ba4a2423/handlebars-4.1.2.jar/handlebars-v4.0.4.js
MD5: 0a63d1ca4ab84541fd1a105f019046be
SHA1: 5023f4d2269fa0b21105e99f809d39034d30c363
SHA256:26ab46ac1b5741e48758c2c924e3d4c31257eb6e3cfda555ef43c866114c3654

pkg:javascript/handlebars@4.0.4  (Confidence:Highest)

References:
info - https://github.com/wycats/handlebars.js/commit/7372d4e9dffc9d70c09671aa28b9392a1577fd86
info - https://snyk.io/vuln/SNYK-JS-HANDLEBARS-173692
Disallow calling helperMissing and blockHelperMissing directly (RETIREJS)  suppress

Disallow calling helperMissing and blockHelperMissing directly
Unscored:
Severity: low

References:
info - https://github.com/wycats/handlebars.js/blob/master/release-notes.md#v430---september-24th-2019
Prototype pollution (RETIREJS)  suppress

Prototype pollution
Unscored:
Severity: medium

References:
info - https://github.com/wycats/handlebars.js/blob/master/release-notes.md#v453---november-18th-2019

**Comment by alexmnyc** [comment]
switching to mustache... thanks

**Comment by jknack** [comment]
hey, you can use the handlebars.js version you want using: `handlebars.handlebarsJsFile(location)`

but yea choose any library that works better for you

**Comment by alexmnyc** [comment]
@jknack hey Edgar. sorry, the issue is that the OWASP vulerable version of the JS file is packaged inside the jar and it gets flagged by enterprise security. It's not an issue in being able to use a different js file. I hope it makes sense

**Comment by alexmnyc** [comment]
It's just a matter of bumping the js file version inside the lib and republishign a new version

**Comment by krassib** [comment]
@jknack - agree with @alex. The corporate security scanners are flagging the embedded js file. Please update it to the latest and repackage. Hope not a huge hassle for you.  
Thanks,
Krass

**Comment by jknack** [comment]
ok, guys will try to do it this weekend... hope to not break any existing test.

**Comment by alexmnyc** [comment]
Thanks!

**Comment by krassib** [comment]
Thanks, man! That will be awesome!

**Comment by jknack** [comment]
4.2.0 released. Give Maven central one/two of hours.

https://github.com/jknack/handlebars.java/releases/tag/v4.2.0

Thanks
