### ISSUE TITLE
“NoSuchMethodErrors” due to multiple versions of com.google.guava:guava:jar

### ISSUE THREAD

**Issue by Bing-ok** [jknack/handlebars.java#792]
## Issue description
Hi, there are multiple versions of **_com.google.guava:guava_** in **_handlebars.java-4.2.0\handlebars-maven-plugin_**. As shown in the following dependency tree, according to Maven's “nearest wins” strategy, only **_com.google.guava:guava:21.0_** can be loaded, **_com.google.guava:guava:16.0.1_**, **_com.google.guava:guava:18.0_**, **_com.google.guava:guava:20.0_** and **_com.google.guava:guava:22.0_** will be shadowed.

However, several methods defined in shadowed version **_com.google.guava:guava:22.0_** are referenced by client project via **_com.google.javascript:closure-compiler:v20180506_**, but missing in the actually loaded version **_com.google.guava:guava:21.0_**.

For instance, the following missing methods(defined in **_com.google.guava:guava:22.0_**) is actually referenced by **_handlebars.java-4.2.0\handlebars-maven-plugin_**, which will introduce a runtime error(i.e., "NoSuchMethodErrors") into **_handlebars.java-4.2.0\handlebars-maven-plugin_**.

**_1. com.google.common.collect.Comparators: java.lang.Object lambda$emptiesFirst$1(java.util.Optional)_** is invoked by **_handlebars.java-4.2.0\handlebars-maven-plugin_** via the following path:
<pre><code>
paths------
&lt;com.github.jknack.handlebars.maven.HandlebarsPlugin: java.net.URL[] projectClasspath()&gt; handlebars.java-4.2.0\handlebars-maven-plugin\target\classes
&lt;com.google.common.collect.Lists$TransformingRandomAccessList: java.lang.Object get(int)&gt; Repositories\com\google\javascript\closure-compiler\v20180506\closure-compiler-v20180506.jar
&lt;com.google.javascript.jscomp.bundle.CachedTransformer$transform__246: java.lang.Object apply(java.lang.Object)&gt; 
&lt;com.google.javascript.jscomp.bundle.Source$Transformer$apply__215: com.google.javascript.jscomp.bundle.Source transform(com.google.javascript.jscomp.bundle.Source)&gt;  
&lt;com.google.common.collect.Comparators$lambda_emptiesFirst_1__55: java.lang.Object apply(java.lang.Object)&gt;  
&lt;com.google.common.collect.Comparators: java.lang.Object lambda$emptiesFirst$1(java.util.Optional)&gt;
</code></pre>

**_2. com.google.common.collect.Multisets: java.util.Spliterator lambda$spliteratorImpl$2(com.google.common.collect.Multiset$Entry)_** is invoked by **_handlebars.java-4.2.0\handlebars-maven-plugin_** via the following path:
<pre><code>
paths------
&lt;com.github.jknack.handlebars.maven.HandlebarsPlugin: java.net.URL[] projectClasspath()&gt; handlebars.java-4.2.0\handlebars-maven-plugin\target\classes
&lt;com.google.common.collect.Lists$TransformingRandomAccessList: java.lang.Object get(int)&gt; Repositories\com\google\javascript\closure-compiler\v20180506\closure-compiler-v20180506.jar
&lt;com.google.javascript.jscomp.bundle.CachedTransformer$transform__246: java.lang.Object apply(java.lang.Object)&gt;  
&lt;com.google.javascript.jscomp.bundle.Source$Transformer$apply__215: com.google.javascript.jscomp.bundle.Source transform(com.google.javascript.jscomp.bundle.Source)&gt;  
&lt;com.google.common.collect.Multisets$lambda_spliteratorImpl_2__157: java.lang.Object apply(java.lang.Object)&gt; 
&lt;com.google.common.collect.Multisets: java.util.Spliterator lambda$spliteratorImpl$2(com.google.common.collect.Multiset$Entry)&gt;
</code></pre>

**_3. com.google.common.collect.Comparators: java.lang.Object lambda$emptiesLast$2(java.util.Optional)_** is invoked by **_handlebars.java-4.2.0\handlebars-maven-plugin_** via the following path:
<pre><code>
paths------
&lt;com.github.jknack.handlebars.maven.HandlebarsPlugin: java.net.URL[] projectClasspath()&gt; handlebars.java-4.2.0\handlebars-maven-plugin\target\classes
&lt;com.google.common.collect.Lists$TransformingRandomAccessList: java.lang.Object get(int)&gt; Repositories\com\google\javascript\closure-compiler\v20180506\closure-compiler-v20180506.jar
&lt;com.google.javascript.jscomp.bundle.CachedTransformer$transform__246: java.lang.Object apply(java.lang.Object)&gt; 
&lt;com.google.javascript.jscomp.bundle.Source$Transformer$apply__215: com.google.javascript.jscomp.bundle.Source transform(com.google.javascript.jscomp.bundle.Source)&gt; 
&lt;com.google.common.collect.Comparators$lambda_emptiesLast_2__56: java.lang.Object apply(java.lang.Object)&gt; 
&lt;com.google.common.collect.Comparators: java.lang.Object lambda$emptiesLast$2(java.util.Optional)&gt;
</code></pre>

## Suggested fixing solutions
1. Upgrade direct dependency <b><i>com.google.guava:guava</i></b> from <b><i>21.0</i></b> to <b><i>22.0-rc1</i></b>. Because version <b><i>22.0-rc1</i></b> includes the above missing method and is compatible with other versions of <b><i>com.google.guava:guava</i></b> in the project.
2. Change dependency <b><i>com.google.javascript:closure-compiler</i></b> from <b><i>v20180506</i></b> to <b><i>v20180101</i></b>. Because the newer version <b><i>com.google.javascript:closure-compiler:v20180101</i></b> does not invoke the above missing methods, such changing can solve the problem.

Please let me know which solution do you prefer? I can submit a PR to fix it.

Thank you very much for your attention.
Best regards,

## Dependency tree----
<pre><code>
[INFO] com.github.jknack:handlebars-maven-plugin:maven-plugin:4.2.0
[INFO] +- org.apache.maven:maven-core:jar:3.5.3:compile
[INFO] |  +- org.apache.maven:maven-model-builder:jar:3.5.3:compile
[INFO] |  |  \- (com.google.guava:guava:jar:18.0:compile - version managed from 20.0; omitted for duplicate)
[INFO] |  +- com.google.inject:guice:jar:no_aop:4.0:compile
[INFO] |  |  \- (com.google.guava:guava:jar:18.0:compile - version managed from 16.0.1; omitted for duplicate)
[INFO] |  \- (com.google.guava:guava:jar:18.0:compile - version managed from 22.0; omitted for conflict with 21.0)
[INFO] +- com.google.javascript:closure-compiler:jar:v20180506:compile
[INFO] |  \- <b>(com.google.guava:guava:jar:18.0:compile - version managed from 22.0; omitted for duplicate)</b>
[INFO] \- <b>com.google.guava:guava:jar:21.0:compile</b>
</code></pre>

**Comment by Bing-ok** [comment]
Could you help me review this issue? 👍 Thanks! @jknack

**Comment by Bing-ok** [comment]
Could you help me review this issue? 👍 Thanks! @jknack

**Comment by jknack** [comment]
Fixed with #881

**Comment by Bing-ok** [comment]
Thanks for your support!
