### ISSUE TITLE
Cannot resolve plugin com.github.jknack:handlebars-maven-plugin:4.2.1-SNAPSHOT

### ISSUE THREAD

**Issue by szuelch** [jknack/handlebars.java#851]
Hi,
I forked the master and opened the project in Intellij IDE. When maven tries to sync the sources it fails and says that it cannot  resolve plugin com.github.jknack:handlebars-maven-plugin:4.2.1-SNAPSHOT. I'm not sure if it is directly related to this error but all Plugins in the sonatype profile can't be found either. Does anyone have an idea on how to fix this?
Thanks in advance for your support.

**Comment by jknack** [comment]
you need to run `mvn clean install` first.
