### ISSUE TITLE
Accessing parent scopes by accident

### ISSUE THREAD

**Issue by jontro** [jknack/handlebars.java#86]
Currently handlebars.java seems to differ in implementation to handlebars.js when it comes to resolving parent scopes.  

I posted a comment on their issue tracker: https://github.com/wycats/handlebars.js/issues/346

Depending on the result of the outcome of this discussion I would like to report my real issue:

Since I need to check a value in handlebars.java in the current scope that always exists in the parent scope but not always in the current scope I thought I could checking this using  {{this.value}}. 

However if value returns UNRESOLVED by the ValueResolver it will go to the parent looking for it. Is there a way to not touch the parent scope?

**Comment by tonysparks** [comment]
Could you add a configuration property to either enable/disable the parent scope resolution?

Something like:

```Java
/* Default setting is true */
handlerbars.parentScopeResolution(boolean enabled)
handlerbars.setParentScopeResolution(boolean enabled)
```

For our use-case, it is a real pain to prefix all of our properties with ```this.```

**Comment by jknack** [comment]
sure... if you raise a new ticket ;)
