### ISSUE TITLE
White space control?

### ISSUE THREAD

**Issue by jernst** [jknack/handlebars.java#862]
My understanding is that syntax like this
```
{{ foo -}}
```
is supposed to be helping with white space control, but it does not seem to be implemented? How do I control whitespace in something like:

```
{{# each ... }}
{{#     unless @first }}
{{#       if @last }}
    and
{{/       if }}
{{#       unless @last }}
    ,
{{/       unless }}
{{/     unless }}

{{  something }}
{{/ each }}
```

so the comma can be right after the last "something"?

**Comment by jknack** [comment]
There is a pretty-print option: https://github.com/jknack/handlebars.java#pretty-print

Also `{{foo~}}`. See: https://github.com/jknack/handlebars.java/issues/251
