### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by Kobee1203** [jknack/handlebars.java#868]
I see that there has not been a release for over a year, and that there are a lot of unresolved PRs.

There is no commit for more than a year.

Does the project need help or new maintainers?

I want to decide if I should replace Handlebars.java with another library.

**Comment by jknack** [comment]
Not anymore. Back on track

**Comment by TWiStErRob** [comment]
I'm thinking about using this library with Micronaut and also found a potential error handling improvement I wanted to contribute, but given the activity in the recent years I'm wondering if this is the right choice to invest my time in. What do you think @jknack?
