### ISSUE TITLE
Upgrade handlebars.js to 4.7.7

### ISSUE THREAD

**Issue by justshot** [jknack/handlebars.java#869]
There is a list of vulnerabilities for handlebars.js below 4.7.7. (https://snyk.io/vuln/npm:handlebars)

The recommendation is to upgrade to 4.7.7.
https://mvnrepository.com/artifact/org.webjars.npm/handlebars/4.7.7

**Comment by jknack** [comment]
done in https://github.com/jknack/handlebars.java/pull/855
