### ISSUE TITLE
plugin: remove Guava from project

### ISSUE THREAD

**Issue by jknack** [jknack/handlebars.java#881]
- replace with Caffeine see #833

**Comment by chrylis** [comment]
Does this imply that a breaking (I suppose minor) update is coming? If so, I'd like to contribute a bit of breaking cleanup.

**Comment by jknack** [comment]
yea need to be minor to follow more or less the handlebars.js versioning which is still around 4.x. Otherwise, will get all kind of questions about it.

In my mind we need:

- pom cleanup
- remove guava from handlebars core (don;'t think it is there)
- add a caffeine cache module
- delete guava cache module
