### ISSUE TITLE
Stackoverflow error with partial

### ISSUE THREAD

**Issue by jontro** [jknack/handlebars.java#95]
We are using a recursive handlebars template which gives us a really weird stackoverflow error under certain conditions

<pre>
/hbs/start.hbs
{{#with page.children.[0]}}
    {{>hbs/navigation/sitemap-level-1}}
{{/with }}

/hbs/navigation/sitemap-level-1.hbs:
{{#each this.children}} 
    {{title}}
    {{>hbs/navigation/sitemap-level-1}}
{{/each}}
</pre>

This works fine. However if I do the following in start.hbs:

<pre>
{{#with page.children.[0]}}
    {{>hbs/navigation/sitemap-level-1}}
{{/with }}
{{#with page.children.[0]}}
    {{>hbs/navigation/sitemap-level-1}}
{{/with }}
</pre>

I get the following exception
java.lang.StackOverflowError at 

<pre>
com.github.jknack.handlebars.internal.TemplateList.remove(TemplateList.java:93) at 
com.github.jknack.handlebars.internal.Partial.remove(Partial.java:75) at 
com.github.jknack.handlebars.internal.TemplateList.remove(TemplateList.java:93) at 
com.github.jknack.handlebars.internal.Block.remove(Block.java:168) at 
com.github.jknack.handlebars.internal.TemplateList.remove(TemplateList.java:93) at 
com.github.jknack.handlebars.internal.Block.remove(Block.java:168) at 
com.github.jknack.handlebars.internal.TemplateList.remove(TemplateList.java:93) at 
repeated...
</pre>

Any clues on how I can debug this issue? I am using version 0.6.2

**Comment by anto-pt** [comment]
I'm getting the infinite loop issue if I'm trying to use the already loaded partial fragment. Even after setting up handlebars.setInfiniteLoops(true), it doesn't work properly. Now I'm getting StackOverflowError. Any help would be appreciate.
